### ISSUE TITLE
Clusterblast downloads failing

### ISSUE THREAD

**Issue by olsonanl** [antismash/antismash#162]
**Describe the bug**
I've installed 5-0-0rc1 on a Redhat 6 system using python 3.7.3.

Clusterblast fails to download:

```
$ env PATH=/disks/patric-common/runtime/bin:$PATH  /disks/patric-common/runtime/antismash-5-0-0rc1/bin/download-antismash-databases --database-dir /vol/patric3/production/data/antismash/antismash-5-0-0rc1
/disks/patric-common/runtime/antismash-5-0-0rc1/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
Creating checksum of Pfam-A.hmm
PFAM file present and ok for version 27.0
Creating checksum of Pfam-A.hmm
PFAM file present and ok for version 31.0
Resfams database present and checked
Downloading ClusterBlast database.
Traceback (most recent call last):
  File "/disks/patric-common/runtime/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/disks/patric-common/runtime/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/disks/patric-common/runtime/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/disks/patric-common/runtime/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/disks/patric-common/runtime/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/disks/patric-common/runtime/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/disks/patric-common/runtime/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/disks/patric-common/runtime/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/disks/patric-common/runtime/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/disks/patric-common/runtime/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/disks/patric-common/runtime/antismash-5-0-0rc1/lib/python3.7/site-packages/antismash/download_databases.py", line 82, in download_file
    req = request.urlopen(url)
  File "/disks/patric-common/runtime/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/disks/patric-common/runtime/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/disks/patric-common/runtime/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/disks/patric-common/runtime/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/disks/patric-common/runtime/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/disks/patric-common/runtime/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/disks/patric-common/runtime/antismash-5-0-0rc1/bin/download-antismash-databases", line 11, in <module>
    load_entry_point('antismash==5.0.0rc1', 'console_scripts', 'download-antismash-databases')()
  File "/disks/patric-common/runtime/antismash-5-0-0rc1/lib/python3.7/site-packages/antismash/download_databases.py", line 352, in _main
    download(args)
  File "/disks/patric-common/runtime/antismash-5-0-0rc1/lib/python3.7/site-packages/antismash/download_databases.py", line 330, in download
    download_clusterblast(args.database_dir)
  File "/disks/patric-common/runtime/antismash-5-0-0rc1/lib/python3.7/site-packages/antismash/download_databases.py", line 307, in download_clusterblast
    download_if_not_present(CLUSTERBLAST_URL, archive_filename, CLUSTERBLAST_ARCHIVE_CHECKSUM)
  File "/disks/patric-common/runtime/antismash-5-0-0rc1/lib/python3.7/site-packages/antismash/download_databases.py", line 207, in download_if_not_present
    download_file(url, filename)
  File "/disks/patric-common/runtime/antismash-5-0-0rc1/lib/python3.7/site-packages/antismash/download_databases.py", line 84, in download_file
    raise DownloadError("ERROR: File not found on server.\nPlease check your internet connection.")
antismash.download_databases.DownloadError: ERROR: File not found on server.
Please check your internet connection.
```

I have installed the latest certifi package, and verified it holds the root certificate 
"DST Root CA X3" that your site uses via LetsEncrypt.

**Expected behavior**
download-databases pulls the databases properly

**To Reproduce**
Install 5-0-0rc1 on a Redhat 6 system using python 3.7.3 via a python venv.

**Screenshots**
Pasted text above

**System (please complete the following information):**
 - OS: CentOS 6.10
 - Browser: N/A

**Additional context**

**Comment by SJShaw** [comment]
This initial error in the log makes me think there's still an intermediate certificate issue on your system:
`unable to get local issuer certificate (_ssl.c:1056)`

I've tested on my Debian machine and it functions, though I'll try getting machine running CentOS to see if I can really narrow it down to certificates. In the meantime, could you try downloading it directly (either via `wget` or browser on that machine) using the same URL as in the script (https://dl.secondarymetabolites.org/releases/clusterblast/clusterblast_20190415.tar.xz)? If they don't succeed, the problem is definitely somewhere in the certificate chain on your machine, hopefully they'll give you an error message which will give extra information to work with.

**Comment by olsonanl** [comment]
Curl and wget both pulled the data properly. 

I seem to recall seeing something while googling about hosts misconfigured with LetsEncrypt not supplying the intermediate certificate when they should; however I don't know if that would explain this failure given that the curl/wget worked properly.

**Comment by SJShaw** [comment]
It's possible there's something in the python networking stack that isn't functioning as expected with your machine's setup. That said, we just use the python standard lib `urllib` package, so I wouldn't really expect it to have issues like this.

Does this python snippet raise any errors?
```
import urllib
url = "https://dl.secondarymetabolites.org/releases/5.0.0rc1/MD5SUM.txt"
urllib.request.urlopen(url)
```

**Comment by olsonanl** [comment]
Yup, same error:

```
olson@spruce:~$ /disks/patric-common/runtime/bin/python3 x.py
Traceback (most recent call last):
  File "/disks/patric-common/runtime/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/disks/patric-common/runtime/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/disks/patric-common/runtime/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/disks/patric-common/runtime/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/disks/patric-common/runtime/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/disks/patric-common/runtime/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/disks/patric-common/runtime/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/disks/patric-common/runtime/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/disks/patric-common/runtime/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/disks/patric-common/runtime/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "x.py", line 3, in <module>
    assert "antismash" in str(request.urlopen(url).read())
  File "/disks/patric-common/runtime/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/disks/patric-common/runtime/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/disks/patric-common/runtime/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/disks/patric-common/runtime/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/disks/patric-common/runtime/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/disks/patric-common/runtime/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
```

However I'm seeing that going to google as well, so something else is going on. This was a fairly fresh install of python, so perhaps there's some bits missing somewhere.

Aha; now I remember. To get the latest python to build on centos6, I had to do a private install of openssl. It didn't have the cert package installed. Adding the certs to .../ssl/cert.pem fixed it.

(And it apparently doesn't matter that at the python level it had the certificates installed).
