### ISSUE TITLE
genefinding disabled

### ISSUE THREAD

**Issue by rdmtinez** [antismash/antismash#183]
**Describe the bug**
I'm trying to run antiSMASH with the Docker image that was downloaded today around 1500hrs (Germany Time) as follows:

`bash run_antismash-full input.fna '/output/folder' --cb-general --cb-knownclusters --cb-subclusters --asf --pfam2go`

However I keep getting the following error, I keep getting the following error:

```
WARNING  12/07 13:14:50   Fasta header too long: renamed "Chlamy10_contig_108" to "c00108_Chlamy1.."
. . . many of these . . .
WARNING  12/07 13:14:50   Fasta header too long: renamed "Chlamy10_contig_109" to "c00109_Chlamy1.."

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/usr/local/lib/python3.5/dist-packages/antismash/common/record_processing.py", line 239, in ensure_cds_info
    genefinding(sequence, options)
  File "/usr/local/lib/python3.5/dist-packages/antismash/detection/genefinding/__init__.py", line 93, in run_on_record
    raise ValueError("Called find_genes, but genefinding disabled")
ValueError: Called find_genes, but genefinding disabled
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/antismash", line 11, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.5/dist-packages/antismash/__main__.py", line 124, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/lib/python3.5/dist-packages/antismash/__main__.py", line 113, in main
    antismash.run_antismash(sequence, options)
  File "/usr/local/lib/python3.5/dist-packages/antismash/main.py", line 574, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/usr/local/lib/python3.5/dist-packages/antismash/main.py", line 628, in _run_antismash
    cast(AntismashModule, genefinding))
  File "/usr/local/lib/python3.5/dist-packages/antismash/common/record_processing.py", line 388, in pre_process_sequences
    sequences = parallel_function(partial, ([sequence] for sequence in sequences))
  File "/usr/local/lib/python3.5/dist-packages/antismash/common/subprocessing/base.py", line 132, in parallel_function
    results = jobs.get(timeout=timeout)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
ValueError: Called find_genes, but genefinding disabled
Running antiSMASH FAILED
```

I'm fairly certain I've installed Docker and the image correctly, as I followed the instructions on the docs pages. 

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 .

**Comment by zachcp** [comment]
try adding the following to your command line options:

```--genefinding-tool prodigal```

**Comment by SJShaw** [comment]
I'm closing this as the solution was given. Feel free to reopen if you want to add anything.

**Comment by JNdurubing** [comment]
great!!!
