### ISSUE TITLE
Error during Java version check

### ISSUE THREAD

**Issue by aozalevsky** [antismash/antismash#225]
Antismash fails  prerequisite check during installation with following traceback:

```
silwer@ibch@dna ~ $ antismash --check-prereqs
/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
Traceback (most recent call last):
  File "/home/domain/silwer/.local/bin/antismash", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/domain/silwer/.local/lib/python3.6/site-packages/antismash/__main__.py", line 126, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/home/domain/silwer/.local/lib/python3.6/site-packages/antismash/__main__.py", line 115, in main
    antismash.run_antismash(sequence, options)
  File "/home/domain/silwer/.local/lib/python3.6/site-packages/antismash/main.py", line 612, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/home/domain/silwer/.local/lib/python3.6/site-packages/antismash/main.py", line 619, in _run_antismash
    _log_found_executables(options)
  File "/home/domain/silwer/.local/lib/python3.6/site-packages/antismash/main.py", line 718, in _log_found_executables
    version = " ({})".format(version_getter())  # pylint: disable=not-callable
  File "/home/domain/silwer/.local/lib/python3.6/site-packages/antismash/common/subprocessing/java.py", line 21, in run_java_version
    raise RuntimeError(msg % java)
RuntimeError: unexpected output from java: /usr/bin/java, check path

```

though java works just fine:

```
silwer@ibch@dna ~ $ java --version
Picked up _JAVA_OPTIONS: -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dawt.useSystemAAFontSettings=on
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
```

The reason for the crash is the presence of the custom _JAVA_OPTIONS, which were set through environmental vars. If I unset them, then antismash passes all the checks.

```
silwer@ibch@dna ~ $ unset _JAVA_OPTIONS
silwer@ibch@dna ~ $ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
silwer@ibch@dna ~ $ antismash --check-prereqs
/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
All prerequisites satisfied
```

It seems, that the root of the problem is https://github.com/antismash/antismash/blob/master/antismash/common/subprocessing/java.py

with a very basic check:

```
def run_java_version() -> str:
    """ Get the version of the java binary """
    java = get_config().executables.java
    command = [
        java,
        "-version",
    ]

    version_string = execute(command).stderr
    if not version_string.startswith("openjdk") and not version_string.startswith("java"):
        msg = "unexpected output from java: %s, check path"
        raise RuntimeError(msg % java)
    # get rid of the non-version stuff in the output
    return version_string.split()[2].strip('"')

```
which fails due to the usage of startswith function. the issue can be solved by this naive check:

`if not "openjdk" in version_string and not "java" in version_string:`

**Comment by kblin** [comment]
Thanks for the report. Java's habit of printing the version string on `stderr` instead of `stdout` is really annoying, because when it then insists to print the `_JAVA_OPTIONS` they get in the way.

The naive check avoids the runtime error, but won't return the right version string. But I've got an idea how to fix this, I'll have a patch once I get into the office a bit later today.

**Comment by kblin** [comment]
Just to double-check, the line with the java version when you have `_JAVA_OPTIONS` set, does that really say `openjdk 11.0.6 2020-01-14` while saying `openjdk version "11.0.6" 2020-01-14` without options set?

**Comment by kblin** [comment]
For me the only thing `_JAVA_OPTIONS` changes is the first line of the output, the rest is unaffected.

**Comment by aozalevsky** [comment]
it seems to be the difference between `-version` and `--version`

```
    -version      print product version to the error stream and exit                                                                                                                                                                       
    --version     print product version to the output stream and exit 
```
```
silwer@ibch@dna ~ $ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
silwer@ibch@dna ~ $ env | grep _JAVA_OPTIONS
_JAVA_OPTIONS=-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dawt.useSystemAAFontSettings=on
silwer@ibch@dna ~ $ java -version
Picked up _JAVA_OPTIONS: -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dawt.useSystemAAFontSettings=on
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
silwer@ibch@dna ~ $ java --version
Picked up _JAVA_OPTIONS: -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dawt.useSystemAAFontSettings=on
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
silwer@ibch@dna ~ $ unset _JAVA_OPTIONS
silwer@ibch@dna ~ $ env | grep _JAVA_OPTIONS
silwer@ibch@dna ~ $ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
silwer@ibch@dna ~ $ java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
```
