### ISSUE TITLE
RuntimeError: diamond failed to run: blastp -> dvancement of Science

### ISSUE THREAD

**Issue by deliacp** [antismash/antismash#242]
Hi all,

I am running antismash in Mac installed with conda.
The command I am trying to execute is 

```
antismash --cb-knownclusters --genefinding-gff3 GCF_000009045.1_ASM904v1_genomic.gff GCF_000009045.1_ASM904v1_genomic.fna
```

This gives the following output:

```
/Users/dcasas/anaconda3/envs/antismash/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
/Users/dcasas/anaconda3/envs/antismash/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
Traceback (most recent call last):
  File "/Users/dcasas/anaconda3/envs/antismash/bin/antismash", line 10, in <module>
    sys.exit(entrypoint())
  File "/Users/dcasas/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/__main__.py", line 126, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/Users/dcasas/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/__main__.py", line 115, in main
    antismash.run_antismash(sequence, options)
  File "/Users/dcasas/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 612, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/Users/dcasas/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 676, in _run_antismash
    analysis_timings = analyse_record(record, options, analysis_modules, module_results)
  File "/Users/dcasas/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 265, in analyse_record
    run_module(record, module, options, previous_result, timings)
  File "/Users/dcasas/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 237, in run_module
    results = module.run_on_record(record, results, options)
  File "/Users/dcasas/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/__init__.py", line 150, in run_on_record
    results.knowncluster = run_knownclusterblast_on_record(record, options)
  File "/Users/dcasas/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/known.py", line 90, in run_knownclusterblast_on_record
    return perform_knownclusterblast(options, record, clusters, proteins)
  File "/Users/dcasas/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/known.py", line 114, in perform_knownclusterblast
    blastoutput = run_diamond_on_all_regions(record.get_regions(), _get_datafile_path('proteins'))
  File "/Users/dcasas/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/core.py", line 82, in run_diamond_on_all_regions
    stdout = subprocessing.run_diamond_search(temp_file.name, database, mode="blastp", opts=extra_args)
  File "/Users/dcasas/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/subprocessing/diamond.py", line 68, in run_diamond_search
    return run_diamond(mode, args).stdout
  File "/Users/dcasas/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/subprocessing/diamond.py", line 42, in run_diamond
    raise RuntimeError("diamond failed to run: %s -> %s" % (subcommand, result.stderr[-100:]))
RuntimeError: diamond failed to run: blastp -> dvancement of Science
Documentation, support and updates available at http://www.diamondsearch.org
```

Any idea of what could be wrong?
I am not sure if this is related to antiSMASH or it is something else. Any help would be really appreciated.

**Comment by kblin** [comment]
Hi,
it looks like diamond is throwing some sort of lengthy error. Could you confirm that you are running version 0.9.30 of diamond? Running "diamond --version" should give you that information.

**Comment by deliacp** [comment]
Yes, that is the version.

```
diamond v0.9.30.131 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

diamond version 0.9.30
```

**Comment by kblin** [comment]
Ah, that might be the problem right there. On previous versions, all that Max Planck kerfuffle wasn't there and it'd simply say
```
diamond version 0.9.24
```
Let me fetch a copy of 0.9.30 and see what happens for me.

**Comment by deliacp** [comment]
Forcing diamond ot version 0.9.24 worked :)
The issue is solved.
Thank you

**Comment by kblin** [comment]
I've managed to follow up with a colleague who had the same issue on his Mac, and it seems that the 0.9.30 version of diamond is build with some CPU features that older Macs don't support, so the operating system kills the diamond blastp run for trying to use a CPU instruction that's not available.

There's nothing we can do about this on the antiSMASH side, maybe file a bug with bioconda about this?
