### ISSUE TITLE
Error handling scikit-learn version 0.22.2.post1

### ISSUE THREAD

**Issue by dettmanj** [antismash/antismash#246]
**Bug:**
Thanks for maintaining AntiSMASH and creating v5 for conda.

After creating and activating a new conda environment:
```
conda create -n antismash
conda activate antismash
```
the install process `conda install antismash` fails and rolls back the transaction:
```
...
Downloading and Extracting Packages
python-3.7.6         | 52.9 MB   | ############################################################################# | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'bioconda::antismash-5.1.1-py_0'.
Rolling back transaction: done

LinkError: post-link script failed for package bioconda::antismash-5.1.1-py_0
location of failed script: <path_to>/antismash/bin/.antismash-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: <path_to>/antismash/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
Traceback (most recent call last):
  File "<path_to>/antismash/bin/download-antismash-databases", line 7, in <module>
    from antismash.download_databases import _main
  File "<path_to>/antismash/lib/python3.7/site-packages/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "<path_to>/antismash/lib/python3.7/site-packages/antismash/main.py", line 44, in <module>
    from antismash.modules import (active_site_finder,
  File "<path_to>/antismash/lib/python3.7/site-packages/antismash/modules/lanthipeptides/__init__.py", line 13, in <module>
    from antismash.common.external.rodeo_svm.rebuild import pickle_classifier
  File "<path_to>/antismash/lib/python3.7/site-packages/antismash/common/external/rodeo_svm/rebuild.py", line 9, in <module>
    from .svm_classify import save_classifier
  File "<path_to>/antismash/lib/python3.7/site-packages/antismash/common/external/rodeo_svm/svm_classify.py", line 76, in <module>
    sklearn_int_versions = list(map(int, sklearn.__version__.split('.')))
ValueError: invalid literal for int() with base 10: 'post1'

return code: 1

()
```
I checked joblib and it seems fine:
```
pip install joblib
Requirement already satisfied: joblib in /usr/lib/python2.7/dist-packages
```
I am a user, not a programmer, so any help you can provide would be appreciated. Thanks.

**System:**
Ubuntu 18.04.4 LTS

**Comment by tamuanand** [comment]
I also had the same issue. @SJShaw  suggested some fixes - please see https://github.com/antismash/antismash/issues/245

**Comment by dettmanj** [comment]
Thanks for the suggestion. I did see your post #245 , but your issue seems to be with downloading the PFam database via FTP. I don't see that reflected in my error messages

**Comment by tamuanand** [comment]
In my opinion, I think your specific install is failing at scikit-learn 

https://github.com/antismash/antismash/issues/245#issuecomment-594667890
and 
https://github.com/antismash/antismash/issues/245#issuecomment-594673396
