### ISSUE TITLE
Bioconda installation error

### ISSUE THREAD

**Issue by rsiani** [antismash/antismash#250]
Thank you for delivering this extremely useful tool.

When trying to install with "conda install -c bioconda antismash" I get this message error:

LinkError: post-link script failed for package bioconda::antismash-5.1.1-py_0
location of failed script: /home/rsiani/miniconda3/bin/.antismash-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: /home/rsiani/miniconda3/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
Traceback (most recent call last):
  File "/home/rsiani/miniconda3/bin/download-antismash-databases", line 7, in <module>
    from antismash.download_databases import _main
  File "/home/rsiani/miniconda3/lib/python3.7/site-packages/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/home/rsiani/miniconda3/lib/python3.7/site-packages/antismash/main.py", line 44, in <module>
    from antismash.modules import (active_site_finder,
  File "/home/rsiani/miniconda3/lib/python3.7/site-packages/antismash/modules/lanthipeptides/__init__.py", line 13, in <module>
    from antismash.common.external.rodeo_svm.rebuild import pickle_classifier
  File "/home/rsiani/miniconda3/lib/python3.7/site-packages/antismash/common/external/rodeo_svm/rebuild.py", line 9, in <module>
    from .svm_classify import save_classifier
  File "/home/rsiani/miniconda3/lib/python3.7/site-packages/antismash/common/external/rodeo_svm/svm_classify.py", line 76, in <module>
    sklearn_int_versions = list(map(int, sklearn.__version__.split('.')))
ValueError: invalid literal for int() with base 10: 'post1'

return code: 1

()

Any idea how to solve it? I was really looking forward to use antiSMASH for my analysis.

Bests, Rob

**Comment by SJShaw** [comment]
This issue was already reported in #246, fixed in #248, and released in 5.1.2. As of an hour ago, bioconda updated to antiSMASH 5.1.2, so you should be fine to just attempt reinstalling.
