### ISSUE TITLE
"genefinding disabled" Error when running --cb-knownclusters option

### ISSUE THREAD

**Issue by ZepingQu** [antismash/antismash#263]
**Describe the bug**
Got 
ValueError: Called find_genes, but genefinding disabled 
with option --cb-knownclusters.

**To Reproduce**
the gbk file that I'm doing my test run is included in the attachment as a txt file.
[44870.assembled.txt](https://github.com/antismash/antismash/files/4572907/44870.assembled.txt)

here is the full error information:
(antismash) $ antismash --cb-knownclusters --output-dir ./out 44870.assembled.gbk 
/root/anaconda3/envs/antismash/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/root/anaconda3/envs/antismash/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/root/anaconda3/envs/antismash/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/root/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/record_processing.py", line 239, in ensure_cds_info
    genefinding(sequence, options)
  File "/root/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/genefinding/__init__.py", line 89, in run_on_record
    raise ValueError("Called find_genes, but genefinding disabled")
ValueError: Called find_genes, but genefinding disabled
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/antismash/bin/antismash", line 10, in <module>
    sys.exit(entrypoint())
  File "/root/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/__main__.py", line 126, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/root/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/__main__.py", line 115, in main
    antismash.run_antismash(sequence, options)
  File "/root/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 612, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/root/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 666, in _run_antismash
    cast(AntismashModule, genefinding))
  File "/root/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/record_processing.py", line 388, in pre_process_sequences
    sequences = parallel_function(partial, ([sequence] for sequence in sequences))
  File "/root/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/subprocessing/base.py", line 132, in parallel_function
    results = jobs.get(timeout=timeout)
  File "/root/anaconda3/envs/antismash/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: Called find_genes, but genefinding disabled

**System (please complete the following information):**
 - OS: Ubuntu 16.04.3
 - antismash: conda version 5.1.2

**Additional context**
 Error not there with nisin.gbk

**Comment by SJShaw** [comment]
You have a record in your genbank file that contains no genes and you haven't specified what gene-finding should do in this scenario. The default behaviour of genefinding on the commandline is to raise an error (see the `--genefinding-tool` argument for details).
