### ISSUE TITLE
UnicodeEncodeError when running --cb-knownclusters option

### ISSUE THREAD

**Issue by ZepingQu** [antismash/antismash#264]
**Describe the bug**
Got 
UnicodeEncodeError: 'latin-1' codec can't encode character '\u03b1' in position 14800: ordinal not in range(256)
with option --cb-knownclusters.

I checked my gbk file, the given position 14800 is a space instead of an 'alpha' sign suggested by the error message.

**To Reproduce**
the gbk file that I'm doing my test run is included in the attachment as a txt file.
[35302.assembled.gbk.txt](https://github.com/antismash/antismash/files/4572923/35302.assembled.gbk.txt)

here is the full error information:

(antismash) $ antismash --cb-knownclusters --output-dir ./out 35302.assembled.gbk 
/root/anaconda3/envs/antismash/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
Traceback (most recent call last):
  File "/root/anaconda3/envs/antismash/bin/antismash", line 10, in <module>
    sys.exit(entrypoint())
  File "/root/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/__main__.py", line 126, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/root/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/__main__.py", line 115, in main
    antismash.run_antismash(sequence, options)
  File "/root/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 612, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/root/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 676, in _run_antismash
    analysis_timings = analyse_record(record, options, analysis_modules, module_results)
  File "/root/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 265, in analyse_record
    run_module(record, module, options, previous_result, timings)
  File "/root/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 237, in run_module
    results = module.run_on_record(record, results, options)
  File "/root/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/__init__.py", line 150, in run_on_record
    results.knowncluster = run_knownclusterblast_on_record(record, options)
  File "/root/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/known.py", line 90, in run_knownclusterblast_on_record
    return perform_knownclusterblast(options, record, clusters, proteins)
  File "/root/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/known.py", line 116, in perform_knownclusterblast
    prefix="knownclusterblast")
  File "/root/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/core.py", line 531, in write_raw_clusterblastoutput
    handle.write(blast_output)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u03b1' in position 14800: ordinal not in range(256)

**System (please complete the following information):**
 - OS: Ubuntu 16.04.3
 - antismash: conda version 5.1.2

**Additional context**
 Error not there with nisin.gbk

**Comment by SJShaw** [comment]
I can't replicate the issue on my machine with your input. However, from memory `latin-1` is  the default python encoding only when the system environment language isn't set.

If your `LANG` environment variable isn't present or isn't set, use  `export LANG=C.UTF-8` and try running again afterwards.

**Comment by ZepingQu** [comment]
Oh, okay, problem solved. Thank you for your help!
