### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 2821: ordinal not in range(128)  

### ISSUE THREAD

**Issue by grst** [antismash/antismash#272]
I'm trying to run antismash with singularity: 

```
singularity pull docker://antismash/standalone
singularity shell standalone_latest.sif
antismash --help-showall
```

But this fails with the following error: 

```console
Singularity> antismash --help-showall
Traceback (most recent call last):
  File "/usr/local/bin/antismash", line 7, in <module>
    from antismash.__main__ import entrypoint
  File "/usr/local/lib/python3.5/dist-packages/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/usr/local/lib/python3.5/dist-packages/antismash/main.py", line 44, in <module>
    from antismash.modules import (active_site_finder,
  File "/usr/local/lib/python3.5/dist-packages/antismash/modules/nrps_pks/__init__.py", line 14, in <module>
    from .html_output import generate_html, will_handle
  File "/usr/local/lib/python3.5/dist-packages/antismash/modules/nrps_pks/html_output.py", line 16, in <module>
    from .results import NRPS_PKS_Results, CandidateClusterPrediction, UNKNOWN
  File "/usr/local/lib/python3.5/dist-packages/antismash/modules/nrps_pks/results.py", line 15, in <module>
    from .parsers import generate_nrps_consensus
  File "/usr/local/lib/python3.5/dist-packages/antismash/modules/nrps_pks/parsers.py", line 17, in <module>
    from .smiles_generator import load_smiles
  File "/usr/local/lib/python3.5/dist-packages/antismash/modules/nrps_pks/smiles_generator.py", line 40, in <module>
    _SMILES = load_smiles()
  File "/usr/local/lib/python3.5/dist-packages/antismash/modules/nrps_pks/smiles_generator.py", line 27, in load_smiles
    for line in smiles_monomer.readlines():
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 2821: ordinal not in range(128)
```

any suspicion what could be going on there?

**Comment by SJShaw** [comment]
The python3 default encoding should be actual unicode and not ASCII, which makes me think that there's some magic going on in the environment.
if you set the `LANG` environment variable to `C.UTF-8`, does it have the same issue?

**Comment by grst** [comment]
Awesome, that did the trick! 

Is it possible to include that into the Dockerfile? I suspect there might be others who want to run antismash on Singularity, as docker is really limited on HPC. 

Cheers, 
Gregor

**Comment by SJShaw** [comment]
Sounds reasonable to me.

**Comment by SJShaw** [comment]
I went to add it, but apparently it's already [there](https://github.com/antismash/antismash/blob/master/Dockerfile#L7).

I'm not familiar enough with singularity to know why it's being ignored there. How did you add it in order to fix it for singularity?

**Comment by grst** [comment]
Hmm, strange. I don't see why that shouldn't have worked. 

I ran antismash from [nextflow](https://www.nextflow.io/docs/latest/singularity.html) and just added the env var to the command: 
```
LANG=C.UTF-8 antismash [...]
```

**Comment by SJShaw** [comment]
Closing this as old and out of our control with singularity not respecting (if it even still does with modern versions) the container settings.
