### ISSUE TITLE
fail to install conda version

### ISSUE THREAD

**Issue by zhanghaoipp** [antismash/antismash#274]
**Describe the bug**
conda create -n antismash antismash

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda::antismash-5.1.2-py_0'.
Rolling back transaction: done

CondaMultiError: LinkError: post-link script failed for package https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda::antismash-5.1.2-py_0
location of failed script: /home/bac/anaconda2/envs/antismash/bin/.antismash-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout:
stderr: Traceback (most recent call last):
  File "/home/bac/anaconda2/envs/antismash/lib/python3.7/site-packages/helperlibs/bio/seqio.py", line 21, in <module>
    from cStringIO import StringIO
ModuleNotFoundError: No module named 'cStringIO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bac/anaconda2/envs/antismash/bin/download-antismash-databases", line 7, in <module>
    from antismash.download_databases import _main
  File "/home/bac/anaconda2/envs/antismash/lib/python3.7/site-packages/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/home/bac/anaconda2/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 31, in <module>
    from antismash.common import logs, record_processing, serialiser
  File "/home/bac/anaconda2/envs/antismash/lib/python3.7/site-packages/antismash/common/record_processing.py", line 16, in <module>
    from helperlibs.bio import seqio
  File "/home/bac/anaconda2/envs/antismash/lib/python3.7/site-packages/helperlibs/bio/seqio.py", line 23, in <module>
    from Bio._py3k import StringIO
ModuleNotFoundError: No module named 'Bio._py3k'

return code: 1

()

**System (please complete the following information):**
 - OS: ubuntu 14.04
 - conda version: conda 4.8.3

It seems cStringIO was replaced in python 3.x???

**Comment by SJShaw** [comment]
A recent `biopython` version removed their `_py3k` module, which the antiSMASH dependency `bioinf-helperlibs` relied on and caused the error you're seeing there.
`bioinf-helperlibs` has already been [updated](https://github.com/kblin/bioinf-helperlibs/releases/tag/release-0-2-0), so you may just need to force update that first (to 0.2.0).

**Comment by zhanghaoipp** [comment]
Thank you! I succeed this time after update helperlibs first!

**Comment by MeryTouceda** [comment]
Hi, I am trying to install AntiSmash and I am encountering the same error even after uploading` helperlibs` using: 
`conda update helperlibs`

This is the error message: 
`Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: \ 

    Installed package of scikit-learn can be accelerated using scikit-learn-intelex.
    More details are available here: https://intel.github.io/scikit-learn-intelex

    For example:

        $ conda install scikit-learn-intelex
        $ python -m sklearnex my_application.py

    

done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'bioconda::antismash-5.1.2-py_3'.
Rolling back transaction: done

CondaMultiError: LinkError: post-link script failed for package bioconda::antismash-5.1.2-py_3
location of failed script: /home/u14/mtoucedasuarez/software/anaconda2/envs/antismash/bin/.antismash-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: Traceback (most recent call last):
  File "/home/u14/mtoucedasuarez/software/anaconda2/envs/antismash/bin/download-antismash-databases", line 7, in <module>
    from antismash.download_databases import _main
  File "/home/u14/mtoucedasuarez/software/anaconda2/envs/antismash/lib/python3.8/site-packages/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/home/u14/mtoucedasuarez/software/anaconda2/envs/antismash/lib/python3.8/site-packages/antismash/main.py", line 31, in <module>
    from antismash.common import logs, record_processing, serialiser
  File "/home/u14/mtoucedasuarez/software/anaconda2/envs/antismash/lib/python3.8/site-packages/antismash/common/record_processing.py", line 20, in <module>
    from antismash.common.secmet import Record
  File "/home/u14/mtoucedasuarez/software/anaconda2/envs/antismash/lib/python3.8/site-packages/antismash/common/secmet/__init__.py", line 11, in <module>
    from .record import Record
  File "/home/u14/mtoucedasuarez/software/anaconda2/envs/antismash/lib/python3.8/site-packages/antismash/common/secmet/record.py", line 20, in <module>
    from Bio import Alphabet, SeqIO
  File "/home/u14/mtoucedasuarez/software/anaconda2/envs/antismash/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

return code: 1

()`
