### ISSUE TITLE
UnicodeDecodeError: Using the docker container with singularity fails

### ISSUE THREAD

**Issue by openpaul** [antismash/antismash#283]
**Describe the bug**
Using singularity to build the docker container leads to this bug:

```
antismash --help                                                                                              
/usr/local/lib/python3.5/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
Traceback (most recent call last):
  File "/usr/local/bin/antismash", line 7, in <module>
    from antismash.__main__ import entrypoint
  File "/usr/local/lib/python3.5/dist-packages/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/usr/local/lib/python3.5/dist-packages/antismash/main.py", line 44, in <module>
    from antismash.modules import (active_site_finder,
  File "/usr/local/lib/python3.5/dist-packages/antismash/modules/nrps_pks/__init__.py", line 14, in <module>
    from .html_output import generate_html, will_handle
  File "/usr/local/lib/python3.5/dist-packages/antismash/modules/nrps_pks/html_output.py", line 16, in <module>
    from .results import NRPS_PKS_Results, CandidateClusterPrediction, UNKNOWN
  File "/usr/local/lib/python3.5/dist-packages/antismash/modules/nrps_pks/results.py", line 15, in <module>
    from .parsers import generate_nrps_consensus
  File "/usr/local/lib/python3.5/dist-packages/antismash/modules/nrps_pks/parsers.py", line 17, in <module>
    from .smiles_generator import load_smiles
  File "/usr/local/lib/python3.5/dist-packages/antismash/modules/nrps_pks/smiles_generator.py", line 40, in <module>
    _SMILES = load_smiles()
  File "/usr/local/lib/python3.5/dist-packages/antismash/modules/nrps_pks/smiles_generator.py", line 27, in load_smiles
    for line in smiles_monomer.readlines():
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 2821: ordinal not in range(128)
```

**Expected behavior**
Singularity should be able to use the docker container.

**To Reproduce**
```
singularity exec docker://antismash/standalone:5.1.1 antismash --help   
```

**Fix**
I propose a fix by adding the UTF-8 encoding to the smiles loading (see pull request)
https://github.com/antismash/antismash/pull/282

**Comment by openpaul** [comment]
We noticed this might be solvable using env variables, so I'll close this for now. Will update with a solution, once we figured it out.
