### ISSUE TITLE
ModuleNotFoundError: No module named 'antismash.config'

### ISSUE THREAD

**Issue by Oldmagua** [antismash/antismash#289]
when i try to download the database of the antiSmash , the Error is ModuleNotFoundError: No module named 'antismash.config'... what can i do with this !!!

**Comment by Oldmagua** [comment]
Traceback (most recent call last):
  File "/ldata/lianwh/software/miniconda3/envs/antismash5/bin/download-antismash-databases", line 33, in <module>
    sys.exit(load_entry_point('antismash==5.1.2', 'console_scripts', 'download-antismash-databases')())
  File "/ldata/lianwh/software/miniconda3/envs/antismash5/bin/download-antismash-databases", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/ldata/lianwh/software/miniconda3/envs/antismash5/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/ldata/lianwh/software/miniconda3/envs/antismash5/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lianwh/.local/lib/python3.8/site-packages/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/home/lianwh/.local/lib/python3.8/site-packages/antismash/main.py", line 26, in <module>
    from antismash.config import (
ModuleNotFoundError: No module named 'antismash.config'

**Comment by SJShaw** [comment]
There is something wrong with your installation of antiSMASH or your conda environment for it. You shouldn't be able to install it without the `config` module, and if you don't have it nothing else in the `antismash` module will work as expected.

To help, we'll need more information, like how you're trying to run it, how you installed it, and so on.

**Comment by Oldmagua** [comment]
Thank you for your attention! 
here is some information about the installation 
 
conda --version
conda 4.8.4
python 
Python 3.8.3

i had install the antismash = 5.1.2 successfully , but when i run the command "download-antismash-databases" to download the database, then the front Error  was reported , and the antismash=5.1.2 package was download from the github which AntiSmash newly post on line, so it should  be official. I guess if `it` would be problem that the python version which conda default setting was 3.8.3 ，but i'm not sure about it .

**Comment by Oldmagua** [comment]
conda create -n antismash
conda activate antismash
conda install hmmer2 hmmer diamond fasttree prodigal blast muscle glimmerhmm
pip install antismash-5.1.2

something wrong with below:
download-antismash-databases

ERROR report:
ModuleNotFoundError: No module named 'antismash.config'

**Comment by Oldmagua** [comment]
fortunately!  i fix the problem !  it must be something wrong with the python version that install antismash , python 3.8.3 is not satisfied with the antismash5 , so i change the python version to 3.7.8 when i creat the conda env of antismash, the all things was fluently. 

the command i used as follow:

conda create -n  antismash python=3.7
conda activate antismash

conda install hmmer2 hmmer diamond fasttree prodigal blast muscle glimmerhmm
pip install antismash-5-1-2 # i had already download antismash 5.1.2 ,if not , you should download the package first!
download-antismash-databases #here maybe you have trouble with the download database with internet time out, you can download the database to local computer first ,then upload to the server .

the databese-file place :
cd /miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/databases
mkdir -p pfam/27.0
cp Pfam27.0/Pfam-A.hmm.gz pfam/27.0
mkdir -p pfam/31.0
cp Pfam31.0/Pfam-A.hmm.gz pfam/31.0
mkdir -p resfam
cp resfams/Resfams.hmm.gz resfam
cp clusterblast_20190415.tar.xz ./

run `download-antismash-databases` again~

then you will successfully install the antismash-5.1.2 and the database！
