### ISSUE TITLE
antismash installation failing 

### ISSUE THREAD

**Issue by mariamantas** [antismash/antismash#292]
- OS: Linux server (Scientific Linux)

This isn't a bug, but I am following your installation instruction and I am hitting many walls. 

What I've done so far: 

1) conda create -n  antismash python=3.7
2) source ~/miniconda3/bin/activate antismash 

3) Typing "download-antismash-databases" returns the following: 

-bash: download-antismash-databases: command not found

4) I ran the following (believing I was bypassing this issue): 

conda install hmmer2 hmmer diamond fasttree prodigal blast muscle glimmerhmm

5) However, now running "antismash input_file" returns: 

-bash: antismash: command not found

Any thoughts on what's going wrong?

**Comment by kblin** [comment]
I think you followed the [install antiSMASH dependencies via Bioconda](https://docs.antismash.secondarymetabolites.org/install/#dependencies-via-bioconda) guide instead of the [install antiSMASH via Bioconda](https://docs.antismash.secondarymetabolites.org/install/#using-bioconda) guide. That leaves you with a conda env without antiSMASH.
You should be able to fix this using
```
conda activate antismash
conda install antismash
download-antismash-databases
```

**Comment by mariamantas** [comment]
Thank you very much for your help. 

I tried doing it as you suggested and this error came up: 

ERROR conda.core.link:_execute(698): An error occurred while installing package 'bioconda::antismash-5.1.2-py_3'.
Rolling back transaction: done

LinkError: post-link script failed for package bioconda::antismash-5.1.2-py_3
location of failed script: /localdisk/home/s1850364/miniconda3/envs/antismash/bin/.antismash-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: Traceback (most recent call last):
  File "/localdisk/home/s1850364/miniconda3/envs/antismash/bin/download-antismash-databases", line 7, in <module>
    from antismash.download_databases import _main
  File "/localdisk/home/s1850364/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/localdisk/home/s1850364/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 31, in <module>
    from antismash.common import logs, record_processing, serialiser
  File "/localdisk/home/s1850364/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/record_processing.py", line 20, in <module>
    from antismash.common.secmet import Record
  File "/localdisk/home/s1850364/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/secmet/__init__.py", line 11, in <module>
    from .record import Record
  File "/localdisk/home/s1850364/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/secmet/record.py", line 20, in <module>
    from Bio import Alphabet, SeqIO
  File "/localdisk/home/s1850364/miniconda3/envs/antismash/lib/python3.7/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

return code: 1

()



Is there a way to fix this?

**Comment by SJShaw** [comment]
It looks like conda is ignoring the biopython version that antiSMASH specifies. If you downgrade biopython to 1.76, that should solve the problem.

**Comment by HenriqueNiero** [comment]
Hello! I had the same problem with Alphabet. 
Now the following error came up:
ImportError: cannot import name 'joblib' from 'sklearn.externals'
I changed the code to import joblib and the error looks fixed.

**Comment by snayfach** [comment]
I'm having the same problem

**Comment by snayfach** [comment]
This ended up working for me: `conda create -n antismash antismash biopython=1.76`.  For some reason had to install both at same time for it to work.

Though now getting the warning: 

> /home/ec2-user/anaconda3/envs/antismash2/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
>   SELECTOR_TOKENIZER = re.compile(r'''

**Comment by gabriellovate** [comment]
I'm getting the same error using `conda create -n antismash antismash`

**Comment by gabriellovate** [comment]
I tried all the sugestions, when I run `conda create -n antismash antismash biopython=1.76 python=3.7` I receive the following error message:
```Bash
ERROR conda.core.link:_execute(698): An error occurred while installing package 'bioconda::antismash-5.1.2-py_3'.
Rolling back transaction: done
class: LinkError
message:
post-link script failed for package bioconda::antismash-5.1.2-py_3
location of failed script: /home/gabriellovate/anaconda3/envs/antismash/bin/.antismash-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: Downloading PFAM version 27.0
Downloading Pfam-A.hmm.gz: 100.00% downloaded.
Creating checksum of Pfam-A.hmm.gz
Extraction of Pfam-A.hmm.gz finished successfully.
Downloading PFAM version 31.0
Downloading Pfam-A.hmm.gz: 100.00% downloaded.
Creating checksum of Pfam-A.hmm.gz
Extraction of Pfam-A.hmm.gz finished successfully.
Downloading Resfam database

stderr: /home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
Traceback (most recent call last):
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/http/client.py", line 944, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/download_databases.py", line 82, in download_file
    req = request.urlopen(url)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/urllib/request.py", line 1378, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/urllib/request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gabriellovate/anaconda3/envs/antismash/bin/download-antismash-databases", line 10, in <module>
    sys.exit(_main())
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/download_databases.py", line 352, in _main
    download(args)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/download_databases.py", line 328, in download
    download_resfam(args.database_dir)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/download_databases.py", line 249, in download_resfam
    download_if_not_present(url, archive_filename, RESFAM_ARCHIVE_CHECKSUM)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/download_databases.py", line 207, in download_if_not_present
    download_file(url, filename)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/download_databases.py", line 84, in download_file
    raise DownloadError("ERROR: File not found on server.\nPlease check your internet connection.")
antismash.download_databases.DownloadError: ERROR: File not found on server.
Please check your internet connection.

return code: 1

kwargs:
{}

Traceback (most recent call last):
  File "/home/gabriellovate/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/home/gabriellovate/anaconda3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/home/gabriellovate/anaconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
    return getattr(module, func_name)(args, parser)
  File "/home/gabriellovate/anaconda3/lib/python3.8/site-packages/conda/cli/main_create.py", line 41, in execute
    install(args, parser, 'create')
  File "/home/gabriellovate/anaconda3/lib/python3.8/site-packages/conda/cli/install.py", line 317, in install
    handle_txn(unlink_link_transaction, prefix, args, newenv)
  File "/home/gabriellovate/anaconda3/lib/python3.8/site-packages/conda/cli/install.py", line 346, in handle_txn
    unlink_link_transaction.execute()
  File "/home/gabriellovate/anaconda3/lib/python3.8/site-packages/conda/core/link.py", line 249, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "/home/gabriellovate/anaconda3/lib/python3.8/site-packages/conda/core/link.py", line 712, in _execute
    raise CondaMultiError(tuple(concatv(
conda.CondaMultiErrorclass: LinkError
message:
post-link script failed for package bioconda::antismash-5.1.2-py_3
location of failed script: /home/gabriellovate/anaconda3/envs/antismash/bin/.antismash-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: Downloading PFAM version 27.0
Downloading Pfam-A.hmm.gz: 100.00% downloaded.
Creating checksum of Pfam-A.hmm.gz
Extraction of Pfam-A.hmm.gz finished successfully.
Downloading PFAM version 31.0
Downloading Pfam-A.hmm.gz: 100.00% downloaded.
Creating checksum of Pfam-A.hmm.gz
Extraction of Pfam-A.hmm.gz finished successfully.
Downloading Resfam database

stderr: /home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
Traceback (most recent call last):
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/http/client.py", line 944, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/download_databases.py", line 82, in download_file
    req = request.urlopen(url)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/urllib/request.py", line 1378, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/urllib/request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gabriellovate/anaconda3/envs/antismash/bin/download-antismash-databases", line 10, in <module>
    sys.exit(_main())
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/download_databases.py", line 352, in _main
    download(args)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/download_databases.py", line 328, in download
    download_resfam(args.database_dir)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/download_databases.py", line 249, in download_resfam
    download_if_not_present(url, archive_filename, RESFAM_ARCHIVE_CHECKSUM)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/download_databases.py", line 207, in download_if_not_present
    download_file(url, filename)
  File "/home/gabriellovate/anaconda3/envs/antismash/lib/python3.7/site-packages/antismash/download_databases.py", line 84, in download_file
    raise DownloadError("ERROR: File not found on server.\nPlease check your internet connection.")
antismash.download_databases.DownloadError: ERROR: File not found on server.
Please check your internet connection.

return code: 1

kwargs:
{}

: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gabriellovate/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/home/gabriellovate/anaconda3/lib/python3.8/site-packages/conda/cli/main.py", line 152, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/home/gabriellovate/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1371, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/home/gabriellovate/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1082, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/home/gabriellovate/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1113, in handle_exception
    return self.handle_application_exception(exc_val, exc_tb)
  File "/home/gabriellovate/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1129, in handle_application_exception
    self._print_conda_exception(exc_val, exc_tb)
  File "/home/gabriellovate/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1133, in _print_conda_exception
    print_conda_exception(exc_val, exc_tb)
  File "/home/gabriellovate/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1056, in print_conda_exception
    stderrlog.error("\n%r\n", exc_val)
  File "/home/gabriellovate/anaconda3/lib/python3.8/logging/__init__.py", line 1463, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/home/gabriellovate/anaconda3/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/home/gabriellovate/anaconda3/lib/python3.8/logging/__init__.py", line 1586, in handle
    if (not self.disabled) and self.filter(record):
  File "/home/gabriellovate/anaconda3/lib/python3.8/logging/__init__.py", line 807, in filter
    result = f.filter(record)
  File "/home/gabriellovate/anaconda3/lib/python3.8/site-packages/conda/gateways/logging.py", line 60, in filter
    record.msg = record.msg % new_args
  File "/home/gabriellovate/anaconda3/lib/python3.8/site-packages/conda/__init__.py", line 126, in __repr__
    errs.append(e.__repr__())
  File "/home/gabriellovate/anaconda3/lib/python3.8/site-packages/conda/__init__.py", line 65, in __repr__
    return '%s: %s' % (self.__class__.__name__, text_type(self))
  File "/home/gabriellovate/anaconda3/lib/python3.8/site-packages/conda/__init__.py", line 84, in __str__
    return text_type(self.message % self._kwargs)
TypeError: %d format: a number is required, not dict
```

**Comment by gabriellovate** [comment]
I manage to install without errors by reating an empty environment with:
```Bash
conda create -n antismash
conda activate antismash
```
and then installing with:
```Bash
conda install antismash biopython=1.76 python=3.7
```
Not sure what is happening though...

**Comment by peiyaohu** [comment]
antismash  --check-prereqs                                                           (antismash7.0.1) 
ERROR    11/04 23:14:17   antismash.detection.cassis: preqrequisite failure: Failed to locate executable for 'meme'
ERROR    11/04 23:14:17   antismash.detectio

**Comment by SJShaw** [comment]
Just as a reminder, we do not support the bioconda package. 

If you have issues with, or after, a conda installation, then you'll need to report those to bioconda to have them fixed: https://github.com/bioconda/bioconda-recipes
