### ISSUE TITLE
Bio.Alphabet has been removed from Biopython

### ISSUE THREAD

**Issue by sjaenick** [antismash/antismash#293]
On a fresh install of antiSmash (5.1.2), Ubuntu  16.04 LTS, but with own python 3.8.5 compiled from source:

```
$ /vol/mgx-sw/bin/antismash
Traceback (most recent call last):
  File "/vol/mgx-sw/bin/antismash", line 11, in <module>
    load_entry_point('antismash==5.1.2', 'console_scripts', 'antismash')()
  File "/vol/mgx-sw/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/vol/mgx-sw/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/vol/mgx-sw/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/vol/mgx-sw/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/vol/mgx-sw/lib/python3.8/site-packages/antismash-5.1.2-py3.8.egg/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/vol/mgx-sw/lib/python3.8/site-packages/antismash-5.1.2-py3.8.egg/antismash/main.py", line 31, in <module>
    from antismash.common import logs, record_processing, serialiser
  File "/vol/mgx-sw/lib/python3.8/site-packages/antismash-5.1.2-py3.8.egg/antismash/common/record_processing.py", line 20, in <module>
    from antismash.common.secmet import Record
  File "/vol/mgx-sw/lib/python3.8/site-packages/antismash-5.1.2-py3.8.egg/antismash/common/secmet/__init__.py", line 11, in <module>
    from .record import Record
  File "/vol/mgx-sw/lib/python3.8/site-packages/antismash-5.1.2-py3.8.egg/antismash/common/secmet/record.py", line 20, in <module>
    from Bio import Alphabet, SeqIO
  File "/vol/mgx-sw/lib/python3.8/site-packages/biopython-1.78-py3.8-linux-x86_64.egg/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
```

**Comment by HenriqueNiero** [comment]
same in #292
downgrade biopython to 1.76

**Comment by kblin** [comment]
How nice of the Biopython folks to go from "Deprecation warning that offers no alternative solution" to "removed" in one release. As @HenriqueNiero mentioned, for now just use Biopython 1.77 or 1.76.

**Comment by kblin** [comment]
Seems they now have added some recommendations: https://biopython.org/wiki/Alphabet Would be nice to have had that before the release that killed off the feature.

**Comment by bitamo** [comment]
I have the same problem. 
I tried downgrading biopython, but still gey the same error.

**Comment by brendanwee** [comment]
Unfortunately it seems this problem extends to when a user installs from BioConda. I just tried to create a conda antismash venv on MacOS and ran into the same error. Is it possible to do a hotfix on a requirements file do add the necessary version? 
Confident will be able to workaround with a manual install in the meantime.

@bitamo Try going to an even earlier biopython version, or ensure that the python environment you are using is the one downgrading biopython. This has been an issue in our code base as well

**Comment by SJShaw** [comment]
As of 6.0.1, the biopython version was pinned to an exact version to fix this issue.
