### ISSUE TITLE
mdb_env_open: Cannot allocate memory

### ISSUE THREAD

**Issue by nick-youngblut** [antismash/antismash#295]
Command: 

```
antismash --cb-knownclusters --cb-subclusters --asf --cpus 8  \
  --genefinding-tool prodigal   --executable-paths meme=./bin/scripts/meme   \
  --databases /ebio/abt3_projects/databases/antismash/v5/   \
  --output-dir tests/output_bac9/BGCs/antismash/Bacteroides_pectinophilus/ \
  /ebio/abt3_scratch/nyoungblut/LLG_62325884640/genomes/Bacteroides_pectinophilus.fna
```

Output:

```
/ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/bin/antismash", line 10, in <module>
    sys.exit(entrypoint())
  File "/ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/lib/python3.8/site-packages/antismash/__main__.py", line 126, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/lib/python3.8/site-packages/antismash/__main__.py", line 115, in main
    antismash.run_antismash(sequence, options)
  File "/ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/lib/python3.8/site-packages/antismash/main.py", line 612, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/lib/python3.8/site-packages/antismash/main.py", line 676, in _run_antismash
    analysis_timings = analyse_record(record, options, analysis_modules, module_results)
  File "/ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/lib/python3.8/site-packages/antismash/main.py", line 265, in analyse_record
    run_module(record, module, options, previous_result, timings)
  File "/ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/lib/python3.8/site-packages/antismash/main.py", line 237, in run_module
    results = module.run_on_record(record, results, options)
  File "/ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/lib/python3.8/site-packages/antismash/modules/clusterblast/__init__.py", line 142, in run_on_record
    results.internal_homology_groups = internal_homology_blast(record)
  File "/ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/lib/python3.8/site-packages/antismash/modules/clusterblast/core.py", line 506, in internal_homology_blast
    blastoutput = run_internal_blastsearch(query_filename)
  File "/ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/lib/python3.8/site-packages/antismash/modules/clusterblast/core.py", line 244, in run_internal_blastsearch
    make_blastdb(query_filename, "internal_input.fasta")
  File "/ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/lib/python3.8/site-packages/antismash/modules/clusterblast/core.py", line 102, in make_blastdb
    raise RuntimeError("makeblastdb failed to run: %s -> %s" % (command, result.stderr[-100:]))
RuntimeError: makeblastdb failed to run: ['/ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/bin/makeblastdb', '-in', 'internal_input.fasta', '-out', 'internal_input.fasta', '-dbtype', 'prot'] -> Error: mdb_env_open: Cannot allocate memory
```

I provided >200 Gb of memory for the cluster job, so that shouldn't be the issue. The closest thing I can find to a solution is: https://www.biostars.org/p/413294/, but that thread describes a Windows issue, while I'm running Ubuntu 18.04.5

**conda env**

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
antismash                 5.1.2                      py_3    bioconda
bcbio-gff                 0.6.6              pyh864c0ab_1    bioconda
biopython                 1.76             py38h516909a_0    conda-forge
blast                     2.10.1          pl526he19e7b1_1    bioconda
boost-cpp                 1.70.0               h7b93d67_3    conda-forge
bx-python                 0.8.9            py38hb90e610_2    bioconda
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.16.1               h516909a_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cairo                     1.16.0            h3fc0475_1005    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
curl                      7.71.1               he644dc0_6    conda-forge
cycler                    0.10.0                     py_2    conda-forge
diamond                   0.9.36               h56fc30b_0    bioconda
entrez-direct             13.9            pl526h375a9b1_0    bioconda
expat                     2.2.9                he1b5a44_2    conda-forge
fasttree                  2.1.10               h516909a_4    bioconda
fontconfig                2.13.1            h1056068_1002    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
ghostscript               9.53.1               he1b5a44_0    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
glib                      2.66.0               h0dae87d_0    conda-forge
glimmerhmm                3.0.4           pl526hf484d3e_3    bioconda
graphite2                 1.3.13            he1b5a44_1001    conda-forge
harfbuzz                  2.7.2                hee91db6_0    conda-forge
helperlibs                0.2.1                      py_0    bioconda
hmmer                     3.1b2                         3    bioconda
hmmer2                    2.3.2                h516909a_4    bioconda
icu                       67.1                 he1b5a44_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.16.0                     py_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
kiwisolver                1.2.0            py38hbf85e49_0    conda-forge
krb5                      1.17.1               hfafb76e_3    conda-forge
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.35                 h769bd43_9    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_6    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h24d8f2e_16    conda-forge
libgfortran-ng            7.5.0               hdf63c60_16    conda-forge
libgomp                   9.3.0               h24d8f2e_16    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_4    conda-forge
libpng                    1.6.37               hed695b0_2    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               hdf63c60_16    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               h68273f3_2    conda-forge
libxslt                   1.1.33               h572872d_1    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markupsafe                1.1.1            py38h1e0a361_1    conda-forge
matplotlib-base           3.3.2            py38h91b0d89_0    conda-forge
meme                      4.11.2          py38pl526hda4a46b_6    bioconda
muscle                    3.8.1551             hc9558a2_5    bioconda
ncurses                   6.2                  he1b5a44_1    conda-forge
numpy                     1.19.1           py38hbc27379_2    conda-forge
olefile                   0.46                       py_0    conda-forge
openjdk                   11.0.8               hacce0ff_0    conda-forge
openssl                   1.1.1g               h516909a_1    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
perl-app-cpanminus        1.7044                  pl526_1    bioconda
perl-archive-tar          2.32                    pl526_0    bioconda
perl-base                 2.23                    pl526_1    bioconda
perl-business-isbn        3.004                   pl526_0    bioconda
perl-business-isbn-data   20140910.003            pl526_0    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-cgi                  4.44            pl526h14c3975_1    bioconda
perl-common-sense         3.74                    pl526_2    bioconda
perl-compress-raw-bzip2   2.087           pl526he1b5a44_0    bioconda
perl-compress-raw-zlib    2.087           pl526hc9558a2_0    bioconda
perl-constant             1.33                    pl526_1    bioconda
perl-data-dumper          2.173                   pl526_0    bioconda
perl-digest-hmac          1.03                    pl526_3    bioconda
perl-digest-md5           2.55                    pl526_0    bioconda
perl-encode               2.88                    pl526_1    bioconda
perl-encode-locale        1.05                    pl526_6    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.002001                pl526_0    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-file-listing         6.04                    pl526_1    bioconda
perl-file-path            2.16                    pl526_0    bioconda
perl-file-temp            0.2304                  pl526_2    bioconda
perl-html-parser          3.72            pl526h6bb024c_5    bioconda
perl-html-tagset          3.20                    pl526_3    bioconda
perl-html-template        2.97                    pl526_1    bioconda
perl-html-tree            5.07                    pl526_1    bioconda
perl-http-cookies         6.04                    pl526_0    bioconda
perl-http-daemon          6.01                    pl526_1    bioconda
perl-http-date            6.02                    pl526_3    bioconda
perl-http-message         6.18                    pl526_0    bioconda
perl-http-negotiate       6.01                    pl526_3    bioconda
perl-io-compress          2.087           pl526he1b5a44_0    bioconda
perl-io-html              1.001                   pl526_2    bioconda
perl-io-socket-ssl        2.066                   pl526_0    bioconda
perl-io-zlib              1.10                    pl526_2    bioconda
perl-json                 4.02                    pl526_0    bioconda
perl-json-xs              2.34            pl526h6bb024c_3    bioconda
perl-libwww-perl          6.39                    pl526_0    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-lwp-mediatypes       6.04                    pl526_0    bioconda
perl-lwp-protocol-https   6.07                    pl526_4    bioconda
perl-mime-base64          3.15                    pl526_1    bioconda
perl-mozilla-ca           20180117                pl526_1    bioconda
perl-net-http             6.19                    pl526_0    bioconda
perl-net-ssleay           1.88            pl526h90d6eec_0    bioconda
perl-ntlm                 1.09                    pl526_4    bioconda
perl-parent               0.236                   pl526_1    bioconda
perl-pathtools            3.75            pl526h14c3975_1    bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
perl-socket               2.027                   pl526_1    bioconda
perl-storable             3.15            pl526h14c3975_0    bioconda
perl-test-requiresinternet 0.05                    pl526_0    bioconda
perl-time-local           1.28                    pl526_1    bioconda
perl-try-tiny             0.30                    pl526_1    bioconda
perl-types-serialiser     1.0                     pl526_2    bioconda
perl-uri                  1.76                    pl526_0    bioconda
perl-www-robotrules       6.02                    pl526_3    bioconda
perl-xml-namespacesupport 1.12                    pl526_0    bioconda
perl-xml-parser           2.44_01         pl526ha1d75be_1002    conda-forge
perl-xml-sax              1.02                    pl526_0    bioconda
perl-xml-sax-base         1.09                    pl526_0    bioconda
perl-xml-sax-expat        0.51                    pl526_3    bioconda
perl-xml-simple           2.25                    pl526_1    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
perl-yaml                 1.29                    pl526_0    bioconda
pigz                      2.3.4                hed695b0_1    conda-forge
pillow                    7.2.0            py38h9776b28_1    conda-forge
pip                       20.2.3                     py_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
prodigal                  2.6.3                h516909a_2    bioconda
pthread-stubs             0.4               h14c3975_1001    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyscss                    1.3.7            py38h1e0a361_1    conda-forge
pysvg-py3                 0.2.2.post3      py38h32f6830_1    conda-forge
python                    3.8.5           h1103e12_8_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-lzo                1.12            py38h47b17db_1001    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
scikit-learn              0.23.2           py38hee58b96_0    conda-forge
scipy                     1.5.2            py38h8c5af15_0    conda-forge
setuptools                49.6.0           py38h32f6830_1    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               h4cf870e_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   6.0.4            py38h1e0a361_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-inputproto           2.3.2             h14c3975_1002    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxi                1.7.10               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxtst              1.2.3             h516909a_1002    conda-forge
xorg-recordproto          1.14.2            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1009    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge
```

**Comment by SJShaw** [comment]
That's strange. My first guess would be some kind of unusual gene name is tricking blast. Is it possible to get a copy of your input file? 

If not, change the `query_filename` variable in [antismash.modules.clusterblast.core](https://github.com/antismash/antismash/blob/master/antismash/modules/clusterblast/core.py#L504) (see your stack trace above for the location in your environment) to be some absolute path you have access to.

When it crashes, you can then try looking at the content and running `makeblastdb` on it outside antiSMASH.

**Comment by nick-youngblut** [comment]
The issue only occurs when I submit the job to our cluster. The OS for both the local and cluster jobs are Ubuntu 18.04.5. Still, when I try to run antismash interactively from a cluster node, I get a segmentation fault (even just using `antismash -h`). I'm surprised that I'm getting such an error with the same OS on each machine. On both local and nodes, I'm using `antismash    5.1.2   py_3    bioconda`

**Comment by nick-youngblut** [comment]
Also, it appears that reverting back to antismash v5.1.1 (for debugging) isn't an option:

```
$ conda install antismash=5.1.1
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.8.5

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c

  added / updated specs:
    - antismash=5.1.1


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    antismash-5.1.1            |             py_0        35.9 MB  bioconda
    blast-2.2.31               |  pl526he19e7b1_5        14.4 MB  bioconda
    ------------------------------------------------------------
                                           Total:        50.3 MB

The following NEW packages will be INSTALLED:

  matplotlib         conda-forge/linux-64::matplotlib-3.3.2-0

The following packages will be DOWNGRADED:

  antismash                                      5.1.2-py_3 --> 5.1.1-py_0
  blast                              2.10.1-pl526he19e7b1_1 --> 2.2.31-pl526he19e7b1_5


Proceed ([y]/n)?


Downloading and Extracting Packages
blast-2.2.31         | 14.4 MB   | ################################################################################################################# | 100%
antismash-5.1.1      | 35.9 MB   | ################################################################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'bioconda::antismash-5.1.1-py_0'.
Rolling back transaction: done

LinkError: post-link script failed for package bioconda::antismash-5.1.1-py_0
location of failed script: /ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/bin/.antismash-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout:
stderr: Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/bin/download-antismash-databases", line 7, in <module>
    from antismash.download_databases import _main
  File "/ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/lib/python3.8/site-packages/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/lib/python3.8/site-packages/antismash/main.py", line 44, in <module>
    from antismash.modules import (active_site_finder,
  File "/ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/lib/python3.8/site-packages/antismash/modules/lanthipeptides/__init__.py", line 13, in <module>
    from antismash.common.external.rodeo_svm.rebuild import pickle_classifier
  File "/ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/lib/python3.8/site-packages/antismash/common/external/rodeo_svm/rebuild.py", line 9, in <module>
    from .svm_classify import save_classifier
  File "/ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/lib/python3.8/site-packages/antismash/common/external/rodeo_svm/svm_classify.py", line 57, in <module>
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib' from 'sklearn.externals' (/ebio/abt3_projects/software/dev/llg/.snakemake/conda/51e2651c/lib/python3.8/site-packages/sklearn/externals/__init__.py)

return code: 1

()
```

**Comment by SJShaw** [comment]
If just `antismash -h` causes a segfault, then changing antiSMASH version is really unlikely to help.

Is the cluster set up with individual nodes pooling resources or are you requesting a single node from the cluster that has 200 Gb of physical RAM?

**Comment by nick-youngblut** [comment]
The segfault happened if I ran an interactive session with < 20 Gb of memory. Why would antismash require so much memory just to run `antismash -h`? 

I'm requesting a single node with 200G of h_vmem

**Comment by SJShaw** [comment]
According to the process status info, running `antismash -h` for me has a peak of 96Mb resident memory. A default analysis of a full genome had a peak of 0.5Gb.

There's only two options I can think of:
- you're asking for megabytes instead of gigabytes in your job request
- the system/cluster isn't configured correctly or has some system issue with loading python

It's definitely not something antiSMASH has any control over.

**Comment by nick-youngblut** [comment]
Antismash is showing a low memory usage for my `antismash -h` jobs, but it still requires >= 10 Gb (I was mistaken about 20 Gb, it's just 10). From qacct:

`antismash -h` job with 8 Gb:

```
==============================================================
qname        short.q
hostname     node513
group        ebio
owner        nyoungblut
project      NONE
department   abt3
jobname      antismash_test.sh
jobnumber    995889
taskid       undefined
account      sge
priority     0
qsub_time    Sun Nov 29 19:45:48 2020
start_time   Sun Nov 29 19:45:50 2020
end_time     Sun Nov 29 19:45:57 2020
granted_pe   parallel
slots        1
failed       0
exit_status  139                  (Segmentation fault)
ru_wallclock 7s
ru_utime     4.721s
ru_stime     2.147s
ru_maxrss    93.379KB
ru_ixrss     0.000B
ru_ismrss    0.000B
ru_idrss     0.000B
ru_isrss     0.000B
ru_minflt    208602
ru_majflt    0
ru_nswap     0
ru_inblock   0
ru_oublock   424
ru_msgsnd    0
ru_msgrcv    0
ru_nsignals  0
ru_nvcsw     13322
ru_nivcsw    401219
cpu          6.867s
mem          145.269MBs
io           22.305MB
iow          0.000s
maxvmem      78.185MB
arid         undefined
ar_sub_time  undefined
category     -l h_rt=3540,h_vmem=8G -pe parallel 1
```

`antismash -h` job with 10 Gb:

```
==============================================================
qname        short.q
hostname     node513
group        ebio
owner        nyoungblut
project      NONE
department   abt3
jobname      antismash_test.sh
jobnumber    995888
taskid       undefined
account      sge
priority     0
qsub_time    Sun Nov 29 19:44:09 2020
start_time   Sun Nov 29 19:44:20 2020
end_time     Sun Nov 29 19:44:29 2020
granted_pe   parallel
slots        1
failed       0
exit_status  0
ru_wallclock 9s
ru_utime     6.121s
ru_stime     2.529s
ru_maxrss    99.750KB
ru_ixrss     0.000B
ru_ismrss    0.000B
ru_idrss     0.000B
ru_isrss     0.000B
ru_minflt    239921
ru_majflt    0
ru_nswap     0
ru_inblock   0
ru_oublock   432
ru_msgsnd    0
ru_msgrcv    0
ru_nsignals  0
ru_nvcsw     16452
ru_nivcsw    460366
cpu          8.651s
mem          250.179MBs
io           38.946MB
iow          0.000s
maxvmem      96.924MB
arid         undefined
ar_sub_time  undefined
category     -l h_rt=3540,h_vmem=10G -pe parallel 1
```

**Comment by nick-youngblut** [comment]
> the system/cluster isn't configured correctly or has some system issue with loading python 

Python runs just fine in jobs with <10 Gb of memory.

I ran antismash on 9 bacterial genomes, and 2 succeeded with 40 Gb of memory, while all 7 others failed even when I used 288 Gb of memory per job. All failed with the error: 

```
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llg/.snakemake/conda/04cba6bc/bin/antismash", line 10, in <module>
    sys.exit(entrypoint())
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llg/.snakemake/conda/04cba6bc/lib/python3.8/site-packages/antismash/__main__.py", line 126, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llg/.snakemake/conda/04cba6bc/lib/python3.8/site-packages/antismash/__main__.py", line 115, in main
    antismash.run_antismash(sequence, options)
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llg/.snakemake/conda/04cba6bc/lib/python3.8/site-packages/antismash/main.py", line 612, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llg/.snakemake/conda/04cba6bc/lib/python3.8/site-packages/antismash/main.py", line 676, in _run_antismash
    analysis_timings = analyse_record(record, options, analysis_modules, module_results)
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llg/.snakemake/conda/04cba6bc/lib/python3.8/site-packages/antismash/main.py", line 265, in analyse_record
    run_module(record, module, options, previous_result, timings)
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llg/.snakemake/conda/04cba6bc/lib/python3.8/site-packages/antismash/main.py", line 237, in run_module
    results = module.run_on_record(record, results, options)
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llg/.snakemake/conda/04cba6bc/lib/python3.8/sit
e-packages/antismash/modules/clusterblast/__init__.py", line 142, in run_on_record
    results.internal_homology_groups = internal_homology_blast(record)
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llg/.snakemake/conda/04cba6bc/lib/python3.8/site-packages/antismash/modules/clusterblast/core.py", line 506, in internal_homology_blast
    blastoutput = run_internal_blastsearch(query_filename)
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llg/.snakemake/conda/04cba6bc/lib/python3.8/site-packages/antismash/modules/clusterblast/core.py", line 244, in run_internal_blastsearch
    make_blastdb(query_filename, "internal_input.fasta")
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llg/.snakemake/conda/04cba6bc/lib/python3.8/site-packages/antismash/modules/clusterblast/core.py", line 102, in make_blastdb
    raise RuntimeError("makeblastdb failed to run: %s -> %s" % (command, result.stderr[-100:]))
RuntimeError: makeblastdb failed to run: ['/ebio/abt3_projects/software/dev/ll_pipelines/llg/.snakemake/conda/04cba6bc/bin/makeblastdb', '-in', 'internal_input.fasta', '-out', 'internal_input.fasta', '-dbtype', 'prot'] -> Error: mdb_env_open: Cannot allocate memory
```

I got full BGC output for the 2 genomes that succeeded (Bacteroides coprocola & Bacteroides plebeius), indicating that makeblastdb worked for those genomes.

**Comment by SJShaw** [comment]
There are no environment variables that antiSMASH sets or changes, with the singular exception of setting a default language in the docker container to allow for UTF-8 support.
