### ISSUE TITLE
error downloading databases "diamond failed to run: makedb -> "

### ISSUE THREAD

**Issue by drelo** [antismash/antismash#308]
**Describe the bug**

Problem installing antismash, error at the end of downloading it abruptly ends with `diamond failed to run: makedb -> `

**Expected behavior**

I tried to install antismash in the cluster following the procedure detailed below (I couldn't install directly through conda).

**To Reproduce**

I followed these steps:

```
conda create -n smash python=3.7 biopython=1.76
conda activate smash
conda install hmmer2 hmmer diamond fasttree prodigal blast muscle glimmerhmm
wget https://dl.secondarymetabolites.org/releases/5.2.0/antismash-5.2.0.tar.gz`
tar -zxf antismash-5.2.0.tar.gz 
```
```
pip install ./antismash-5.2.0/conda list

# packages in environment at /mnt/ubi/andres/miniconda3/envs/smash:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
antismash                 5.2.0                    pypi_0    pypi
bcbio-gff                 0.6.6                    pypi_0    pypi
biopython                 1.76             py37h516909a_0    conda-forge
blast                     2.5.0                hc0b0e79_3    bioconda
boost                     1.70.0           py37h9de70de_1    conda-forge
boost-cpp                 1.70.0               h7b93d67_3    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37he5f6b98_2    conda-forge
cycler                    0.10.0                   pypi_0    pypi
diamond                   2.0.4                h56fc30b_0    bioconda
fasttree                  2.1.10               h516909a_4    bioconda
glimmerhmm                3.0.4           pl526hf484d3e_3    bioconda
helperlibs                0.2.1                    pypi_0    pypi
hmmer                     3.3.1                he1b5a44_0    bioconda
hmmer2                    2.3.2                h516909a_4    bioconda
icu                       67.1                 he1b5a44_0    conda-forge
jinja2                    2.11.2                   pypi_0    pypi
joblib                    0.17.0                   pypi_0    pypi
kiwisolver                1.2.0                    pypi_0    pypi
ld_impl_linux-64          2.35                 h769bd43_9    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgfortran-ng            9.3.0               he4bcb1c_17    conda-forge
libgfortran5              9.3.0               he4bcb1c_17    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libopenblas               0.3.10          pthreads_h4812303_5    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.3.2                    pypi_0    pypi
muscle                    3.8.1551             hc9558a2_5    bioconda
ncurses                   6.2                  he1b5a44_2    conda-forge
numpy                     1.19.2           py37h7008fea_1    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
pillow                    8.0.0                    pypi_0    pypi
pip                       20.2.4                     py_0    conda-forge
prodigal                  2.6.3                h516909a_2    bioconda
pyparsing                 2.4.7                    pypi_0    pypi
pyscss                    1.3.7                    pypi_0    pypi
pysvg-py3                 0.2.2.post3              pypi_0    pypi
python                    3.7.8           h6f2ec95_1_cpython    conda-forge
python-dateutil           2.8.1                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
scikit-learn              0.23.2                   pypi_0    pypi
scipy                     1.5.3                    pypi_0    pypi
setuptools                49.6.0           py37he5f6b98_2    conda-forge
six                       1.15.0                   pypi_0    pypi
sqlite                    3.33.0               h4cf870e_1    conda-forge
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.10               hed695b0_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge

Processing ./antismash-5.2.0
Requirement already satisfied: numpy in /mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages (from antismash==5.2.0) (1.19.2)
Requirement already satisfied: biopython<1.77,>=1.71 in /mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages (from antismash==5.2.0) (1.76)
Collecting helperlibs
  Using cached helperlibs-0.2.1-py2.py3-none-any.whl (23 kB)
Collecting jinja2
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting joblib
  Using cached joblib-0.17.0-py3-none-any.whl (301 kB)
Collecting pysvg-py3
  Using cached pysvg_py3-0.2.2.post3-py3-none-any.whl (28 kB)
Processing /export/home/andrespara/.cache/pip/wheels/6a/0c/09/b30112b4ce4394f83d58e962eeb54cedfe54bb776a8051a514/bcbio_gff-0.6.6-py3-none-any.whl
Processing /export/home/andrespara/.cache/pip/wheels/95/82/81/7aea84e7b48c17238b11e41bbdf32363806b537b2cb7ba1bac/pyScss-1.3.7-cp37-cp37m-linux_x86_64.whl
Collecting matplotlib
  Using cached matplotlib-3.3.2-cp37-cp37m-manylinux1_x86_64.whl (11.6 MB)
Collecting scipy
  Downloading scipy-1.5.3-cp37-cp37m-manylinux1_x86_64.whl (25.9 MB)
     |████████████████████████████████| 25.9 MB 45.1 MB/s 
Collecting scikit-learn>=0.19.0
  Using cached scikit_learn-0.23.2-cp37-cp37m-manylinux1_x86_64.whl (6.8 MB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp37-cp37m-manylinux1_x86_64.whl (27 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Requirement already satisfied: certifi>=2020.06.20 in /mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages (from matplotlib->antismash==5.2.0) (2020.6.20)
Collecting pillow>=6.2.0
  Using cached Pillow-8.0.0-cp37-cp37m-manylinux1_x86_64.whl (2.2 MB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.2.0-cp37-cp37m-manylinux1_x86_64.whl (88 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Building wheels for collected packages: antismash
  Building wheel for antismash (setup.py) ... done
  Created wheel for antismash: filename=antismash-5.2.0-py3-none-any.whl size=46325085 sha256=e4fd51edd4bff8add063606ce59917b3176e5587f57ff7af4d38a7d98a84fcdc
  Stored in directory: /export/home/andrespara/.cache/pip/wheels/dc/ff/10/fb3492c3009659d88d01bc36432b4dd7368887c5a02c54a1ab
Successfully built antismash
Installing collected packages: helperlibs, MarkupSafe, jinja2, joblib, pysvg-py3, six, bcbio-gff, pyScss, python-dateutil, cycler, pillow, kiwisolver, pyparsing, matplotlib, scipy, threadpoolctl, scikit-learn, antismash
Successfully installed MarkupSafe-1.1.1 antismash-5.2.0 bcbio-gff-0.6.6 cycler-0.10.0 helperlibs-0.2.1 jinja2-2.11.2 joblib-0.17.0 kiwisolver-1.2.0 matplotlib-3.3.2 pillow-8.0.0 pyScss-1.3.7 pyparsing-2.4.7 pysvg-py3-0.2.2.post3 python-dateutil-2.8.1 scikit-learn-0.23.2 scipy-1.5.3 six-1.15.0 threadpoolctl-2.1.0
(smash) [andrespara@nagual antiSMASH]$ download-antismash-databases
/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
Downloading PFAM version 27.0
Downloading Pfam-A.hmm.gz: 100.00% downloaded.
Creating checksum of Pfam-A.hmm.gz
Extraction of Pfam-A.hmm.gz finished successfully.
Downloading PFAM version 32.0
Downloading Pfam-A.hmm.gz: 100.00% downloaded.
Creating checksum of Pfam-A.hmm.gz
Extraction of Pfam-A.hmm.gz finished successfully.
Downloading Resfam database
Downloading Resfams.hmm.gz: 100.00% downloaded.
Creating checksum of Resfams.hmm.gz
Extraction of Resfams.hmm.gz finished successfully.
Ensuring all cutoffs are present
Downloading ClusterBlast database.
Downloading clusterblast_20201012.tar.xz: 100.00% downloaded.
Creating checksum of clusterblast_20201012.tar.xz
Extraction of clusterblast_20201012.tar.xz finished successfully.
Extraction of clusterblast_20201012.tar finished successfully.
Pre-building all databases...
Error encountered while preparing module data: diamond failed to run: makedb -> 
```

**System (please complete the following information):**
 - OS: CentOS

**Additional context**

I am aware of the complications with Bio.Alphabet reported in recent issues so I tried the fixes recommended at those threads.
 
Thanks for your help
Best,

**Comment by SJShaw** [comment]
That's curious.

If you manually run diamond, does it give you any output when it fails (if it fails)?
`diamond makedb --in $DATA_DIR/clusterblast/proteins.fasta --out $DATA_DIR/clusterblast/proteins.dmnd`
Replace `$DATA_DIR` with wherever you've set your data location for antiSMASH (the default is the `data` directory in the install location).

**Comment by drelo** [comment]
Thanks for your help I just noticed data only contains data/databases but no other files or folders
That line returned me an error
```
 diamond makedb --in data/clusterblast/proteins.fasta --out data/clusterblast/proteins.dmnd
Illegal instruction (core dumped)
```
```
diamond --version
Illegal instruction (core dumped)
```
Should I downgrade diamond?
I have another environment using diamond (v0.9.24) along HUMAnN and it is running.

**Comment by SJShaw** [comment]
You could try re-installing, but I'm almost certain that the version conda is installing was built for a different CPU instruction set so it'll have the same issue.

If you can build a compatible binary from source, that might be worth trying, otherwise use whatever version you know works.

**Comment by drelo** [comment]
Thanks for your help, your line returned me this message (I replaced the former diamond with 0.9.24)    

```
diamond makedb --in data/clusterblast/proteins.fasta --out data/clusterblast/proteins.dmnd
Error: Missing parameter: database file (--db/-d)
```
downloading again the databases 'works' but I see no files in the folder where I executed this line.
```
(smash) [andrespara@nagual antiSMASH]$ download-antismash-databases
/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
Creating checksum of Pfam-A.hmm
PFAM file present and ok for version 27.0
Creating checksum of Pfam-A.hmm
PFAM file present and ok for version 32.0
Downloading Resfam database
Downloading Resfams.hmm.gz: 100.00% downloaded.
Creating checksum of Resfams.hmm.gz
Extraction of Resfams.hmm.gz finished successfully.
Ensuring all cutoffs are present
Creating checksum of proteins.fasta
ClusterBlast fasta file present and checked
Pre-building all databases...
done.
```
Then antismash doesn't work with a short demo.fasta

```
antismash demo.fasta 
/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/antismash/common/record_processing.py", line 239, in ensure_cds_info
    genefinding(sequence, options)
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/antismash/detection/genefinding/__init__.py", line 89, in run_on_record
    raise ValueError("Called find_genes, but genefinding disabled")
ValueError: Called find_genes, but genefinding disabled
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/ubi/andres/miniconda3/envs/smash/bin/antismash", line 8, in <module>
    sys.exit(entrypoint())
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/antismash/__main__.py", line 129, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/antismash/__main__.py", line 118, in main
    antismash.run_antismash(sequence, options)
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/antismash/main.py", line 625, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/antismash/main.py", line 679, in _run_antismash
    cast(AntismashModule, genefinding))
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/antismash/common/record_processing.py", line 388, in pre_process_sequences
    sequences = parallel_function(partial, ([sequence] for sequence in sequences))
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/site-packages/antismash/common/subprocessing/base.py", line 132, in parallel_function
    results = jobs.get(timeout=timeout)
  File "/mnt/ubi/andres/miniconda3/envs/smash/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: Called find_genes, but genefinding disabled
(smash) [andrespara@nagual antiSMASH]$ 
```

**Comment by SJShaw** [comment]
Whoops, I made a mistake in that command, it should have been `--db`, sorry. It looks to be working fine now that you've replaced it though.

`download-antismash-databases` doesn't download to the current working directory, you can specify the directory with command line options, if none are supplied it checks for an antiSMASH config file, and then falls back to that `data` directory in the install location as a last resort.

That last error is because you supplied a FASTA input without specifying a genefinding method. Run with `--help` and look at the choices for `--genefinding-tool` (or `--genefinding-gff3`, if you'll be supplying GFF files).

**Comment by drelo** [comment]
Thanks for your help I was trying `download-antismash-databases -h ` before instead of using the 'help' flag.
I downloaded the databases, used `makedb` as you recommended and then run a simple test with a fasta from GenBank with the `--genefinding-tool prodigal` option.
