### ISSUE TITLE
RuntimeError: unexpected output from blastp: /data/liqingmei/tools/miniconda3/envs/antismash/bin/blastp, check path

### ISSUE THREAD

**Issue by li0604** [antismash/antismash#316]
**Describe the bug**
Dear everyone,
I install the antismash-5-2-0 according the web, https://docs.antismash.secondarymetabolites.org/install/#installing-the-latest-antismash-release
**Expected behavior**

when I give a test, a problem was given as follow:
**the script:** 
#!/bin/sh
#PBS -N antimash_1
#PBS -q cu
#PBS -l nodes=1:ppn=14
#PBS -V
#PBS -S /bin/bash

source activate /data/liqingmei/tools/miniconda3/envs/antismash

/data/liqingmei/tools/miniconda3/envs/antismash/bin/antismash \
--taxon bacteria \
--output-dir /data/liqingmei/test/antismash \
--databases /data/liqingmei/tools/miniconda3/envs/antismash/antismash-5-2-0/antismash/databases \
--genefinding-tool prodigal \
--cpus 14 /data/liqingmei/test/antismash/SQW42.5.fa

the error:
  File "/data/liqingmei/tools/miniconda3/envs/antismash/lib/python3.6/site-packages/antismash/common/subprocessing/blast.py", line 71, in run_blastp_version
    raise RuntimeError(msg % blastp)
RuntimeError: unexpected output from blastp: /data/liqingmei/tools/miniconda3/envs/antismash/bin/blastp, check path

****System (please complete the following information):****

Linux ln01 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.5.1804 (Core) 
Release:	7.5.1804
Codename:	Core

when I find the  /data/liqingmei/tools/miniconda3/envs/antismash/bin/blastp, it is here. 

So I want to understand this problem and how to solve this error .

**Comment by SJShaw** [comment]
Can you show the output of running that blastp with the `-version` argument?

**Comment by li0604** [comment]
/data/liqingmei/tools/miniconda3/envs/antismash/bin/blastp -version
/data/liqingmei/tools/miniconda3/envs/antismash/bin/blastp: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

ll /data/liqingmei/tools/miniconda3/envs/antismash/bin/blastp
-rwxrwxr-x 1 liqingmei wangyong 23747792 Nov 11 17:27 /data/liqingmei/tools/miniconda3/envs/antismash/bin/blastp

**Comment by kblin** [comment]
It looks like your blast install is broken, so this would be an issue with anaconda/bioconda.

**Comment by li0604** [comment]
thanks, i will uninstall it and try again.

**Comment by cylcheyanlin** [comment]
> It looks like your blast install is broken, so this would be an issue with anaconda/bioconda.

Hi, PhD Blin.  I got some trouble and could you give me a hand ? Thank you very much.

When I install the hmmer3.1b2 using conda, it reported the error.

ERROR    02/04 09:44:05   antismash.modules.active_site_finder: preqrequisite failure: Failed to locate file: 'hmmpfam2'
ERROR    02/04 09:44:05   antismash.modules.lanthipeptides: preqrequisite failure: Failed to locate executable for 'hmmpfam2'
ERROR    02/04 09:44:05   antismash.modules.lassopeptides: preqrequisite failure: Failed to locate executable for 'hmmpfam2'
ERROR    02/04 09:44:05   antismash.modules.sactipeptides: preqrequisite failure: Failed to locate executable for 'hmmpfam2'
ERROR    02/04 09:44:05   antismash.modules.thiopeptides: preqrequisite failure: Failed to locate executable for 'hmmpfam2'
Some module prerequisites not satisfied


According to the blog, https://blog.csdn.net/Curry_chenhu/article/details/109894249, I uninstall the version, but it still reported a followed error.

Traceback (most recent call last):
  File "/home/cheyanlin/miniconda3/envs/antismash/bin/antismash", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/cheyanlin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/__main__.py", line 125, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/home/cheyanlin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/__main__.py", line 113, in main
    antismash.run_antismash(sequence, options)
  File "/home/cheyanlin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/main.py", line 673, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/home/cheyanlin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/main.py", line 680, in _run_antismash
    _log_found_executables(options)
  File "/home/cheyanlin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/main.py", line 775, in _log_found_executables
    version = " ({})".format(version_getter())  # pylint: disable=not-callable
  File "/home/cheyanlin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/common/subprocessing/hmmpfam.py", line 72, in run_hmmpfam2_version
    version_line = run_hmmpfam2_help().split('\n')[1]
  File "/home/cheyanlin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/common/subprocessing/hmmpfam.py", line 65, in run_hmmpfam2_help
    raise RuntimeError(msg % hmmpfam2)
RuntimeError: unexpected output from hmmpfam2: /home/cheyanlin/miniconda3/envs/antismash/bin/hmmpfam2, check path

What is the matter? How do I fix it?
