### ISSUE TITLE
Run antismash5.1.2 Error: RuntimeError: Running hmmsearch failed.

### ISSUE THREAD

**Issue by Oldmagua** [antismash/antismash#319]
I used antismash to analysis my Metagenome data, but it came with the problem,
antismsash version:  5.1.2
installed by conda with python 3.7
run code: `antismash -c 20 --taxon bacteria --cb-general --cb-knownclusters --cb-subclusters --asf --pfam2go --genefinding-tool prodigal --output-dir out_path in_path`

Error report info:
while searching /ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/hmm_detection/data/bg
c_seeds.hmm
Traceback (most recent call last):
  File "/ldata/lianwh/software/miniconda3/envs/antismash/bin/antismash", line 8, in <module>
    sys.exit(entrypoint())
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/__main__.py", line 126, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/__main__.py", line 115, in main
    antismash.run_antismash(sequence, options)
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 612, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 672, in _run_antismash
    timings = run_detection(record, options, module_results)
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 167, in run_detection
    run_module(record, cast(AntismashModule, module), options, module_results, timings)
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 237, in run_module
    results = module.run_on_record(record, results, options)
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/hmm_detection/__init__.py", line 149, in run_on_record
    "rule-based-clusters")
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/hmm_rule_parser/cluster_prediction.py", line 395, in detect_protoclusters_and_signatures
    runresults = run_hmmsearch(seeds_file, full_fasta, use_tempfile=True)
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/subprocessing/hmmsearch.py", line 55, in run_hmmsearch
    raise RuntimeError("Running hmmsearch failed.")
RuntimeError: Running hmmsearch failed.

What can i do with this?

**Comment by SJShaw** [comment]
What are the first few lines of output when you run `hmmsearch -h`?

**Comment by Oldmagua** [comment]
run `hmmsearch -h`

# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.3.1 (Jul 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Usage: hmmsearch [options] <hmmfile> <seqdb>

**Comment by Oldmagua** [comment]
there is a different version of  HMMER in antismash environment
when i run 
`conda activate antismash
hmmsearch -h`

# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.3 (Nov 2019); http://hmmer.org/
# Copyright (C) 2019 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Usage: hmmsearch [options] <hmmfile> <seqdb>

Is that any problem with different version of HMMER?

**Comment by SJShaw** [comment]
Only the conda environment is relevant if antiSMASH is being run within the conda environment.

Does this happen for all inputs or just one?

**Comment by Oldmagua** [comment]
i try to run another data, the error was different

Error report info:
ERROR    16/11 17:23:19   hmmsearch returned -6: Fatal exception (source file easel.c, line 2113):
unexpected getcwd() error
 while searching /ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/hmm_detection/data/bg
c_seeds.hmm
Traceback (most recent call last):
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/subprocessing/hmmsearch.py", line
 55, in run_hmmsearch
    raise RuntimeError("Running hmmsearch failed.")
RuntimeError: Running hmmsearch failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ldata/lianwh/software/miniconda3/envs/antismash/bin/antismash", line 8, in <module>
    sys.exit(entrypoint())
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/__main__.py", line 126, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/__main__.py", line 115, in main
    antismash.run_antismash(sequence, options)
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 612, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 672, in _run_antismash
    timings = run_detection(record, options, module_results)
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 167, in run_detection
    run_module(record, cast(AntismashModule, module), options, module_results, timings)
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 237, in run_module
    results = module.run_on_record(record, results, options)
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/hmm_detection/__init__.py", line 149, in run_on_record
    "rule-based-clusters")
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/hmm_rule_parser/cluster_prediction.py", line 395, in detect_protoclusters_and_signatures
    runresults = run_hmmsearch(seeds_file, full_fasta, use_tempfile=True)
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/subprocessing/hmmsearch.py", line 56, in run_hmmsearch
    return list(SearchIO.parse("result.domtab", 'hmmsearch3-domtab'))
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/site-packages/helperlibs/wrappers/io.py", line 34, in __exit__
    shutil.rmtree(self.tempdir)
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/shutil.py", line 485, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/ldata/lianwh/software/miniconda3/envs/antismash/lib/python3.7/shutil.py", line 483, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp389ocaer'

there were two errors?  i don't know why , the commond was same and both in the antismash environment

**Comment by Oldmagua** [comment]
I ran antismash to analyze my  Metagenome data, then the error was coming, but my single genome was OK. Something wrong with analyzing Metagenome data in antismash?

**Comment by SJShaw** [comment]
Metagenomic inputs will tend to have worse results because they're so fragmented, but they should work.

The combination of these two errors makes me think that something on your system is deleting the temporary files/directories that hmmsearch is expecting to be there.

```
hmmsearch returned -6: Fatal exception (source file easel.c, line 2113):
unexpected getcwd() error
...
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp389ocaer'
```

How large is your input? How much RAM do you have? How much disk space is available in /tmp and are there any quota systems in place?

**Comment by Oldmagua** [comment]
first input was 1.9G and second was 2.8G, and totol RAM was 976G
my tmp file seems that more than i know:
```
Filesystem               Size  Used Avail Use% Mounted on
devtmpfs                 489G     0  489G   0% /dev
tmpfs                    489G  5.2M  489G   1% /dev/shm
tmpfs                    489G  256M  488G   1% /run
tmpfs                    489G     0  489G   0% /sys/fs/cgroup
/dev/mapper/centos-root   50G   36G   15G  71% /
/dev/md126p1            1014M  367M  648M  37% /boot
/dev/mapper/centos-home  370G  250G  120G  68% /home
/dev/sda1                4.1T  455G  3.5T  12% /data
tmpfs                     98G  8.0K   98G   1% /run/user/0
/dev/sdf1                 15T   14T  1.1T  94% /software
/dev/sdd1                142T   28T  107T  21% /ldata
/dev/sdg1                 67T   66T  1.5T  98% /mdata
tmpfs                     98G   16K   98G   1% /run/user/42
tmpfs                     98G   40K   98G   1% /run/user/1004
tmpfs                     98G     0   98G   0% /run/user/1005
tmpfs                     98G     0   98G   0% /run/user/1055
tmpfs                     98G   12K   98G   1% /run/user/1035
tmpfs                     98G     0   98G   0% /run/user/1028
tmpfs                     98G     0   98G   0% /run/user/1016
tmpfs                     98G     0   98G   0% /run/user/1017
tmpfs                     98G     0   98G   0% /run/user/1038
tmpfs                     98G     0   98G   0% /run/user/1050
tmpfs                     98G     0   98G   0% /run/user/1039
tmpfs                     98G     0   98G   0% /run/user/1008
```

**Comment by SJShaw** [comment]
Unless `/tmp` is a symlink to one of those other filesystems, you only have 15G free for hmmsearch to write all its output about your 2G inputs. That's also assuming that no other user processes will be writing to that 15G at the time antiSMASH was running.

As it doesn't happen with smaller inputs on your same system, I'm quite sure this is because your `/tmp` is too small to handle the input sizes you're trying to run on. You'll need to reorganise your filesystem, remove the chances of filesystem contention if it's a shared machine, or simply split your massive inputs into chunks and run on those instead.

You can also try editing [this line](https://github.com/antismash/antismash/blob/e2fc85b7276f2de5fb4737d5a8220679b53b5e07/antismash/common/hmm_rule_parser/cluster_prediction.py#L399) in your install to `use_tempfile=False` instead, but that will only avoid temporary files for inputs to hmmsearch, it will still create output files.

**Comment by Oldmagua** [comment]
if that i can set the `tmp`  filepath?  like `--tempfile path` , but i didn't see the command can set it , could you please tell me how to set it? i think default temp file was small , so i want to change it !

**Comment by SJShaw** [comment]
This is a system level change or an environment change, it's not something antiSMASH has a specific option for.

Change the `TMPDIR` environment variable to whichever path you want to use and python will respect that (as long as the directory exists).

**Comment by tamuanand** [comment]
@SJShaw @Oldmagua This below is unrelated to the TMPDIR and conda issues that @Oldmagua is seeing. 

Since this is metagenomic data being analyzed, wouldn't you want to use `prodigal-m` as the gene finding tool?
