### ISSUE TITLE
Using unannotated genomes with local running antismash

### ISSUE THREAD

**Issue by RCAFink** [antismash/antismash#344]
I am trying to run antismash locally using genome assemblies that are not annotated at first using the `--minimal` with the `--genefinder prodigal` options. this is what I got:

```multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/local/anaconda3/envs/antismash5/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/local/anaconda3/envs/antismash5/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/local/anaconda3/envs/antismash5/lib/python3.8/site-packages/antismash/common/record_processing.py", line 237, in ensure_cds_info
    if not options.genefinding_gff3 and options.genefinding_tool != "none":
  File "/Users/local/anaconda3/envs/antismash5/lib/python3.8/site-packages/antismash/config/__init__.py", line 55, in __getattr__
    raise AttributeError("Config has no attribute: %s" % attr)
AttributeError: Config has no attribute: genefinding_gff3
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/local/anaconda3/envs/antismash5/bin/antismash", line 8, in <module>
    sys.exit(entrypoint())
  File "/Users/local/anaconda3/envs/antismash5/lib/python3.8/site-packages/antismash/__main__.py", line 126, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/Users/local/anaconda3/envs/antismash5/lib/python3.8/site-packages/antismash/__main__.py", line 115, in main
    antismash.run_antismash(sequence, options)
  File "/Users/local/anaconda3/envs/antismash5/lib/python3.8/site-packages/antismash/main.py", line 612, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/Users/local/anaconda3/envs/antismash5/lib/python3.8/site-packages/antismash/main.py", line 665, in _run_antismash
    results.records = record_processing.pre_process_sequences(results.records, options,
  File "/Users/local/anaconda3/envs/antismash5/lib/python3.8/site-packages/antismash/common/record_processing.py", line 388, in pre_process_sequences
    sequences = parallel_function(partial, ([sequence] for sequence in sequences))
  File "/Users/local/anaconda3/envs/antismash5/lib/python3.8/site-packages/antismash/common/subprocessing/base.py", line 132, in parallel_function
    results = jobs.get(timeout=timeout)
  File "/Users/local/anaconda3/envs/antismash5/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
AttributeError: Config has no attribute: genefinding_gff3```

I tried several other options (e.g., I ran my assemblies through prodigal first and fed them to antismash as .fna files, tried the`--genefinder none` option, etc) but the result is always the same: it asks for the GFF3 file and defaults to error. 

I have tried with one of the genomes I have been using with the web-based version of the program and I haven't had any problem. Unfortunately, I have a large number of genomes to assess and I can't run them on through the website. 
I am not sure what to do at this point. Maybe creating a GFF3 file? I was wondering if someone else had this problem.

**Comment by RCAFink** [comment]
My original problem was caused by using the argument `--genefinder prodigal` instead of  `--genefinding-tool prodigal` and a broken prodigal install within antismash itself. Using docker sorted it out

**Comment by huiluocao** [comment]
I met with this problem. Can anyone clarify this?

**Comment by SJShaw** [comment]
@huiluocao If you have the exact problem as shown above, then the solution is also provided above.

If you have prodigal installed and you are using the correct antiSMASH option and still have the issue, you'll need to provide some more information for us to work with.
