### ISSUE TITLE
Unbound Local Error while running GutSmash

### ISSUE THREAD

**Issue by Ksherriff** [antismash/antismash#357]
Hi, 

I am attempting to use GutSmash and have run into this error. Running on Ubuntu 20.04. Using the --minimal, --cb-knownclusters, and --enable-genefunctions options. This is the trace back of the error. 

Traceback (most recent call last):
  File "run_gutsmash.py", line 9, in <module>
    entrypoint()
  File "/home/kylacochrane/gutsmash/antismash/__main__.py", line 126, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/home/kylacochrane/gutsmash/antismash/__main__.py", line 115, in main
    antismash.run_antismash(sequence, options)
  File "/home/kylacochrane/gutsmash/antismash/main.py", line 609, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/home/kylacochrane/gutsmash/antismash/main.py", line 688, in _run_antismash
    write_outputs(results, options)
  File "/home/kylacochrane/gutsmash/antismash/main.py", line 408, in write_outputs
    html.write(results.records, module_results_per_record, options)
  File "/home/kylacochrane/gutsmash/antismash/outputs/html/__init__.py", line 98, in write
    generate_webpage(records, results, options)
  File "/home/kylacochrane/gutsmash/antismash/outputs/html/generator.py", line 140, in generate_webpage
    html_sections = generate_html_sections(record_layers_with_regions, results_by_record_id, options)
  File "/home/kylacochrane/gutsmash/antismash/outputs/html/generator.py", line 103, in generate_html_sections
    sections.append(handler.generate_html(region, handler_results, record, options))
  File "/home/kylacochrane/gutsmash/antismash/modules/clusterblast/html_output.py", line 43, in generate_html
    div = generate_div(region_layer, record_layer, options_layer, "knownclusterblast", tooltip)
UnboundLocalError: local variable 'tooltip' referenced before assignment

**Comment by kblin** [comment]
Hi there, this is the antiSMASH issue tracker. Apart from providing the code base for gutSMASH, we really have nothing to do with gutSMASH itself. I'd point you at https://github.com/victoriapascal/gutsmash for filing gutSMASH issues, but I can see that there's no issue tracker enabled on that repository. Maybe @victoriapascal can help?

**Comment by kblin** [comment]
Ah, they've now enabled the issue tracker, so please post your issue over there.
