### ISSUE TITLE
Case when multiple versions of meme coexist

### ISSUE THREAD

**Issue by jinnjy** [antismash/antismash#358]
**Describe the bug**
In the server I used, somebody already install meme version 5.0.5. I installed antismash5 through conda, the message indicated that meme 4.11.2 should have also obtained but antismash used the meme version 5.0.5 originally installed but not the one installed in virtual environment created by conda.

**Expected behavior**
I expect that the analysis should be able to complete successfully but somehow the following message pumped up, which resembled the cases which meme 5.0.5 was called but not meme version 4.11.2 installed together with antismash5.

Sorry I am relatively new to github, but this should resemble the error in the other previous issues.
Traceback (most recent call last):
  File "/home/jinnjy/.conda/envs/antismash5/bin/antismash", line 10, in <module>
    sys.exit(entrypoint())
  File "/home/jinnjy/.conda/envs/antismash5/lib/python3.8/site-packages/antismash/__main__.py", line 126, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/home/jinnjy/.conda/envs/antismash5/lib/python3.8/site-packages/antismash/__main__.py", line 115, in main
    antismash.run_antismash(sequence, options)
  File "/home/jinnjy/.conda/envs/antismash5/lib/python3.8/site-packages/antismash/main.py", line 612, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/home/jinnjy/.conda/envs/antismash5/lib/python3.8/site-packages/antismash/main.py", line 676, in _run_antismash
    analysis_timings = analyse_record(record, options, analysis_modules, module_results)
  File "/home/jinnjy/.conda/envs/antismash5/lib/python3.8/site-packages/antismash/main.py", line 265, in analyse_record
    run_module(record, module, options, previous_result, timings)
  File "/home/jinnjy/.conda/envs/antismash5/lib/python3.8/site-packages/antismash/main.py", line 237, in run_module
    results = module.run_on_record(record, results, options)
  File "/home/jinnjy/.conda/envs/antismash5/lib/python3.8/site-packages/antismash/modules/lanthipeptides/__init__.py", line 111, in run_on_record
    return run_specific_analysis(record)
  File "/home/jinnjy/.conda/envs/antismash5/lib/python3.8/site-packages/antismash/modules/lanthipeptides/specific_analysis.py", line 744, in run_specific_analysis
    run_lanthi_on_genes(record, gene, cluster, neighbours, results)
  File "/home/jinnjy/.conda/envs/antismash5/lib/python3.8/site-packages/antismash/modules/lanthipeptides/specific_analysis.py", line 692, in run_lanthi_on_genes
    result_vec = run_lanthipred(record, candidate, lant_class, domains)
  File "/home/jinnjy/.conda/envs/antismash5/lib/python3.8/site-packages/antismash/modules/lanthipeptides/specific_analysis.py", line 565, in run_lanthipred
    candidate = determine_precursor_peptide_candidate(record, query, domains,
  File "/home/jinnjy/.conda/envs/antismash5/lib/python3.8/site-packages/antismash/modules/lanthipeptides/specific_analysis.py", line 517, in determine_precursor_peptide_candidate
    rodeo_result = run_rodeo(record, query, query.translation[:cleavage_result.end],
  File "/home/jinnjy/.conda/envs/antismash5/lib/python3.8/site-packages/antismash/modules/lanthipeptides/rodeo.py", line 39, in run_rodeo
    fimo_scores = identify_lanthi_motifs(leader, core)
  File "/home/jinnjy/.conda/envs/antismash5/lib/python3.8/site-packages/antismash/modules/lanthipeptides/rodeo.py", line 471, in identify_lanthi_motifs
    fimo_scores[int(parts[0])] = float(parts[5])
ValueError: could not convert string to float: '+'

**To Reproduce**
For analysis issues, provide an accession number or a record fragment that can reproduce the problem.

antismash was installed using the following commands:

conda create -n antismash antismash biopython=1.76
conda activate antismash
conda install antismash
download-antismash-databases

The analysis was performed using the genome assembly with ncbi accession number GCA_000024025.1
The following command was used to perform analysis. 
antismash --output-dir GCA_000024025 --cb-general --cb-knownclusters --cb-subclusters --asf --pfam2go --smcog-trees  --genefinding-tool prodigal GCA_000024025.1_ASM2402v1_genomic.fna

**Screenshots**

**System (please complete the following information):**
CentOS 3.10.0-957.27.2.el7.x86_64

**Additional context**
I personally think that the pipeline get confused by calling the meme 5.0.5 that was already installed. I wonder there is any way to ensure that the pipeline uses all the software installed in the virtual environment but not the duplicated ones outside?

**Comment by SJShaw** [comment]
The version of any binary dependency that will be used by antiSMASH is the one that comes first in your PATH variable. 

The [conda recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/antismash/meta.yaml#L39) for antiSMASH requires MEME <= 4.11.2 and conda should be prioritising the meme install from the conda environment, if it's not, that's a problem with either the conda environment or possibly the conda install itself. 

If you definitely have the right version of MEME installed in the conda environment, then you can work around whatever conda is doing wrong by indicating to antiSMASH you want to use a different binary than the PATH provides using `--executable-paths meme=/path/to/correct/meme`.

**Comment by jinnjy** [comment]
Thank you for the reply. 
It worked after I let the path of the conda environment come first in my PATH variable.
