### ISSUE TITLE
Run antiSMASH errors on Macbook Pro

### ISSUE THREAD

**Issue by wanggj2003** [antismash/antismash#360]
Hi, I have been trying antiSMASH (5.1.1, the newest download version) in miniconda, but having continuous errors. I first tried more command: antismash --cb-general --cb-knownclusters --cb-subclusters --asf --pfam2go --smcog-trees --genefinding-tool prodigal. And just tried one with less, see below, still ended with errors:

(antismash) Guojuns-MacBook-Pro:AVG-54 gwang$ antismash --cb-general --cb-knownclusters --cb-subclusters /Users/gwang/Desktop/AVG54_1.fa --output-dir .
/Users/gwang/miniconda3/envs/antismash/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
WARNING  10/05 11:30:38   Fasta header too long: renamed "scaffold00001_pilon" to "c00001_scaffol.."
/Users/gwang/miniconda3/envs/antismash/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
/Users/gwang/miniconda3/envs/antismash/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
/Users/gwang/miniconda3/envs/antismash/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
/Users/gwang/miniconda3/envs/antismash/lib/python3.8/site-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/gwang/miniconda3/envs/antismash/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/gwang/miniconda3/envs/antismash/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/gwang/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/common/record_processing.py", line 237, in ensure_cds_info
    if not options.genefinding_gff3 and options.genefinding_tool != "none":
  File "/Users/gwang/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/config/__init__.py", line 55, in __getattr__
    raise AttributeError("Config has no attribute: %s" % attr)
AttributeError: Config has no attribute: genefinding_gff3
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gwang/miniconda3/envs/antismash/bin/antismash", line 10, in <module>
    sys.exit(entrypoint())
  File "/Users/gwang/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/__main__.py", line 126, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/Users/gwang/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/__main__.py", line 115, in main
    antismash.run_antismash(sequence, options)
  File "/Users/gwang/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/main.py", line 612, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/Users/gwang/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/main.py", line 665, in _run_antismash
    results.records = record_processing.pre_process_sequences(results.records, options,
  File "/Users/gwang/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/common/record_processing.py", line 388, in pre_process_sequences
    sequences = parallel_function(partial, ([sequence] for sequence in sequences))
  File "/Users/gwang/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/common/subprocessing/base.py", line 132, in parallel_function
    results = jobs.get(timeout=timeout)
  File "/Users/gwang/miniconda3/envs/antismash/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
AttributeError: Config has no attribute: genefinding_gff3

**Comment by SJShaw** [comment]
Does `--check-prereqs` work on its own? If not, try again with `--cpus 1` (both with `--check-prereqs` and your initial arguments if that succeeds).

I don't have a mac to test with, but my current theory for the cause is that something is wrong in the multiprocess portion of python 3.8 on mac.

**Comment by zreitz** [comment]
I encountered the same bug on an M1 Macbook Pro. `--cpus 1` does indeed fix the problem.

`antismash --check-prereqs` returns `All prerequisites satisfied` with or without `--cpus 1`.

The `_Config` instance is still full when `pool.starmap_async(function, args)` is called (antismash/common/subprocessing/base.py", line 127), but it's empty when `ensure_cds_info()` is called from within the subprocess. I don't know enough about multithreading to find out what's happening in between, but let me know if there's anything else you want me to try.

**Comment by SJShaw** [comment]
That definitely sounds like some kind of serialisation issue in python itself.

Which version of python is this with, 3.8? If it is 3.8, trying 3.7 would let me know if that's when the change happened and where to start digging for both causes and test cases to use while working around it.
