### ISSUE TITLE
AntiSMash 6 conda install not working

### ISSUE THREAD

**Issue by Sidduppal** [antismash/antismash#416]
**Describe the bug**
I'm able to install antiSMash on my local server using the following commands but when I try to do the same on a HPC cluster it gives me the following error. A similar issue has been reported [here](https://githubmemory.com/repo/antismash/antismash/issues/390).

Command used:

```
conda create -n antismash -y
conda activate antismash
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda install -y -c bioconda antismash
```

Error:

```
ERROR conda.core.link:_execute(699): An error occurred while installing package 'bioconda::antismash-6.0.1-pyhdfd78af_0'.
Rolling back transaction: done

LinkError: post-link script failed for package bioconda::antismash-6.0.1-pyhdfd78af_0
location of failed script: /var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/bin/.antismash-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: Downloading PFAM version 32.0

stderr: Traceback (most recent call last):
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/urllib/request.py", line 1571, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/urllib/request.py", line 1592, in connect_ftp
    return ftpwrapper(user, passwd, host, port, dirs, timeout,
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/urllib/request.py", line 2413, in __init__
    self.init()
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/urllib/request.py", line 2422, in init
    self.ftp.connect(self.host, self.port, self.timeout)
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/ftplib.py", line 158, in connect
    self.welcome = self.getresp()
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/ftplib.py", line 240, in getresp
    resp = self.getmultiline()
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/ftplib.py", line 226, in getmultiline
    line = self.getline()
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/ftplib.py", line 214, in getline
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/download_databases.py", line 90, in download_file
    req = request.urlopen(url)
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/urllib/request.py", line 1589, in ftp_open
    raise exc.with_traceback(sys.exc_info()[2])
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/urllib/request.py", line 1571, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/urllib/request.py", line 1592, in connect_ftp
    return ftpwrapper(user, passwd, host, port, dirs, timeout,
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/urllib/request.py", line 2413, in __init__
    self.init()
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/urllib/request.py", line 2422, in init
    self.ftp.connect(self.host, self.port, self.timeout)
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/ftplib.py", line 158, in connect
    self.welcome = self.getresp()
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/ftplib.py", line 240, in getresp
    resp = self.getmultiline()
File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/ftplib.py", line 226, in getmultiline
    line = self.getline()
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/ftplib.py", line 214, in getline
    raise EOFError
urllib.error.URLError: <urlopen error ftp error: EOFError()>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/bin/download-antismash-databases", line 10, in <module>
    sys.exit(_main())
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/download_databases.py", line 398, in _main
    download(args)
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/download_databases.py", line 361, in download
    download_pfam(
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/download_databases.py", line 236, in download_pfam
    download_if_not_present(url, archive_filename, archive_checksum)
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/download_databases.py", line 215, in download_if_not_present
    download_file(url, filename)
  File "/var/lib/condor/execute/slot1/dir_13953/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/download_databases.py", line 92, in download_file
    raise DownloadError("ERROR: File not found on server.\nPlease check your internet connection.")
antismash.download_databases.DownloadError: ERROR: File not found on server.
Please check your internet connection.

return code: 1

() 
```
**Expected behavior**

AntiSMash should install.

**System (please complete the following information):**
 - OS: Ubuntu

**Comment by zdk123** [comment]
If ftp is blocked on the cluster, try downloading from https manually. The same data is at:
https://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam34.0/Pfam-A.hmm.gz

The `download-antismash-databases` script smartly won't attempt a download if the output file is already present.

**Comment by zdk123** [comment]
https://dl.secondarymetabolites.org is down for maintenance at the moment.

**Comment by jolespin** [comment]
How can I download the database without docker? Is there a FTP site where I could just wget?

**Comment by adarmitage** [comment]
We have ftp connections blocked on our cluster similar to the original post. Following the advice above, we hope to install the databases manually and then run download-antismash-databases.

Please can you clarify what commands are required to download required database files in a way that later recognised by the download-antismash-databases script?

**Comment by SJShaw** [comment]
Use whichever commands work on your cluster to fetch/transfer the files.
The only important thing is the layout of the data directory (the location of which can be specified with `--database-dir` to `download-antismash-databases` or `--databases` to antiSMASH itself).

The download script includes the expected layout of the directory for each database, e.g. [the Pfam archive](https://github.com/antismash/antismash/blob/19cbf0b39fc58794e7eb5e49f66c1f69cd99ee53/antismash/download_databases.py#L226) would currently be inside that `--database-dir` as `pfam/34.0/Pfam-A.hmm.gz`.
