### ISSUE TITLE
ValueError: could not convert string to float: '+'

### ISSUE THREAD

**Issue by markbessemBC** [antismash/antismash#424]
**Describe the bug**
antiSMASH crashes at lanthipeptide step. This issue happens with both version 6.0.1 and 6.1.0. Is there a specific tool or database that is causing the issue? .gbk file has been generated with prokka 1.14.5.

```
antismash -c 12 --cb-general --cb-knownclusters --cb-subclusters --asf --smcog-trees --output-dir as_out PROKKA_02232022.gbk
Traceback (most recent call last):
  File "/opt/ohpc/pub/apps/antiSMASH/6.1.0-foss-2020b/bin/antismash", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/ohpc/pub/apps/antiSMASH/6.1.0-foss-2020b/lib/python3.8/site-packages/antismash/__main__.py", line 125, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/opt/ohpc/pub/apps/antiSMASH/6.1.0-foss-2020b/lib/python3.8/site-packages/antismash/__main__.py", line 113, in main
    antismash.run_antismash(sequence, options)
  File "/opt/ohpc/pub/apps/antiSMASH/6.1.0-foss-2020b/lib/python3.8/site-packages/antismash/main.py", line 673, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/opt/ohpc/pub/apps/antiSMASH/6.1.0-foss-2020b/lib/python3.8/site-packages/antismash/main.py", line 733, in _run_antismash
    analysis_timings = analyse_record(record, options, get_analysis_modules(), module_results)
  File "/opt/ohpc/pub/apps/antiSMASH/6.1.0-foss-2020b/lib/python3.8/site-packages/antismash/main.py", line 299, in analyse_record
    run_module(record, module, options, previous_result, timings)
  File "/opt/ohpc/pub/apps/antiSMASH/6.1.0-foss-2020b/lib/python3.8/site-packages/antismash/main.py", line 271, in run_module
    results = module.run_on_record(record, results, options)
  File "/opt/ohpc/pub/apps/antiSMASH/6.1.0-foss-2020b/lib/python3.8/site-packages/antismash/modules/lanthipeptides/__init__.py", line 111, in run_on_record
    return run_specific_analysis(record)
  File "/opt/ohpc/pub/apps/antiSMASH/6.1.0-foss-2020b/lib/python3.8/site-packages/antismash/modules/lanthipeptides/specific_analysis.py", line 757, in run_specific_analysis
    run_lanthi_on_genes(record, gene, cluster, neighbours, results)
  File "/opt/ohpc/pub/apps/antiSMASH/6.1.0-foss-2020b/lib/python3.8/site-packages/antismash/modules/lanthipeptides/specific_analysis.py", line 705, in run_lanthi_on_genes
    result_vec = run_lanthipred(record, candidate, lant_class, domains)
  File "/opt/ohpc/pub/apps/antiSMASH/6.1.0-foss-2020b/lib/python3.8/site-packages/antismash/modules/lanthipeptides/specific_analysis.py", line 576, in run_lanthipred
    candidate = determine_precursor_peptide_candidate(record, query, domains,
  File "/opt/ohpc/pub/apps/antiSMASH/6.1.0-foss-2020b/lib/python3.8/site-packages/antismash/modules/lanthipeptides/specific_analysis.py", line 528, in determine_precursor_peptide_candidate
    rodeo_result = run_rodeo(record, query, query.translation[:cleavage_result.end],
  File "/opt/ohpc/pub/apps/antiSMASH/6.1.0-foss-2020b/lib/python3.8/site-packages/antismash/modules/lanthipeptides/rodeo.py", line 39, in run_rodeo
    fimo_scores = identify_lanthi_motifs(leader, core)
  File "/opt/ohpc/pub/apps/antiSMASH/6.1.0-foss-2020b/lib/python3.8/site-packages/antismash/modules/lanthipeptides/rodeo.py", line 470, in identify_lanthi_motifs
    fimo_scores[int(parts[0])] = float(parts[5])
ValueError: could not convert string to float: '+'

```

**Comment by kblin** [comment]
The crash is in parsing of the FIMO results, what version of the MEME suite do you have installed?

**Comment by kblin** [comment]
A quick way to double-check would be to run with the `--without-fimo` parameter to antiSMASH, which should avoid that crash.

**Comment by markbessemBC** [comment]
Meme version 5.4.1, I see now that a specific version of Meme is required, I'll try installing that one and running again, thnx!

**Comment by markbessemBC** [comment]
Can confirm, that fixed the issue. Apologies for not reading the install instructies correctly and thank you for your time!
