### ISSUE TITLE
LinkError: post-link script failed for package bioconda::antismash

### ISSUE THREAD

**Issue by nick-youngblut** [antismash/antismash#437]
environment yaml file:

```
channels:
- conda-forge
- bioconda
dependencies:
- pigz
- bioconda::antismash>=5.1.2
```

mamba install error:

```
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
ERROR conda.core.link:_execute(699): An error occurred while installing package 'bioconda::antismash-5.1.2-py_4'.
Rolling back transaction: ...working... done

LinkError: post-link script failed for package bioconda::antismash-5.1.2-py_4
location of failed script: /tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/bin/.antismash-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout:
stderr: Traceback (most recent call last):
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/bin/download-antismash-databases", line 7, in <module>
    from antismash.download_databases import _main
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/lib/python3.8/site-packages/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/lib/python3.8/site-packages/antismash/main.py", line 35, in <module>
    from antismash.detection import (cassis,
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/lib/python3.8/site-packages/antismash/detection/nrps_pks_domains/__init__.py", line 15, in <module>
    from .domain_drawing import generate_html, generate_js_domains, will_handle
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/lib/python3.8/site-packages/antismash/detection/nrps_pks_domains/domain_drawing.py", line 14, in <module>
    from antismash.common.html_renderer import FileTemplate, HTMLSections
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/lib/python3.8/site-packages/antismash/common/html_renderer.py", line 13, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (/tmp/global2/nyoungblut/code/dev/ll_pipelines/llg/.snakemake/conda/da77e3cc51f5e031e44581821028a307/lib/python3.8/site-packages/jinja2/__init__.py)

return code: 1
```

It appears that `Markup` cannot be imported from `jinja2`. This should be reproducible via any CI approach (e.g., github actions) in which conda/mamba is used for install (e.g., https://github.com/mamba-org/setup-mamba).

My OS: Ubuntu 18.04.6

**Comment by kblin** [comment]
You need to pin jinja2 to a 3.0 version to run such an old antiSMASH release. The jinja2 library changed their exposed exports, and antiSMASH 6.1 properly handles that, but naturally old versions don't.

**Comment by kblin** [comment]
I guess the proper fix would be to pin all library versions in build.yml, but that's a bug you'll have to file with the bioconda project.

**Comment by nick-youngblut** [comment]
Thanks for the quick response! I can confirm that the following results in a successful conda env install:

```
- conda-forge::jinja2=3.0
- bioconda::antismash=6.0.1
```

**Comment by kblin** [comment]
the jinja2 pin will no longer be required once antismash 6.1.0 hits bioconda, but it's currently stuck with some CI issues: https://github.com/bioconda/bioconda-recipes/pull/34096
