### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character '\u03b1' in position 3001633: ordinal not in range(256)

### ISSUE THREAD

**Issue by crueckert-cebitec** [antismash/antismash#451]
**Describe the bug**
Using a local installation, this error is thrown either while running the KnownClusterBlast or while generating the final output. I have not been able to locate the offending entry/entries. Most likely, there is an \alpha in one or more of the database entries.
Two versions at different stages have come up so far: 
1) During Knwon Cluster Blast
2) During creation of the final HTML file

**Expected behavior**
Writing the output using either the proper encoding or changing offending characters into something else.

**To Reproduce**
Attached are two genomes that cause the error messages 1 (01_Pseudomonas_syringae_DSM_1241) and 2 (04_Janthinobacterium_agaricidamnosum_DSM9628)

Call: 
antismash -c 16  --clusterhmmer --cb-general  --asf --cc-mibig --rre  --cb-knownclusters --cb-subclusters --tigrfam  --pfam2go --smcog-trees --output-dir antiSMASH/$name --output-basename $name --html-title  $name --html-description $name --html-start-compact GenBank/$name.gbk

$name containing the basename of the input file

**Error messages**

Below are the errors thrown:

-- Error message 1 --
Traceback (most recent call last):
  File "/prj/nanopore/bin/miniconda3/envs/antismash/bin/antismash", line 8, in <module>
    sys.exit(entrypoint())
  File "/prj/nanopore/bin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/__main__.py", line 125, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/prj/nanopore/bin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/__main__.py", line 113, in main
    antismash.run_antismash(sequence, options)
  File "/prj/nanopore/bin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/main.py", line 673, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/prj/nanopore/bin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/main.py", line 733, in _run_antismash
    analysis_timings = analyse_record(record, options, get_analysis_modules(), module_results)
  File "/prj/nanopore/bin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/main.py", line 299, in analyse_record
    run_module(record, module, options, previous_result, timings)
  File "/prj/nanopore/bin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/main.py", line 271, in run_module
    results = module.run_on_record(record, results, options)
  File "/prj/nanopore/bin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/modules/clusterblast/__init__.py", line 158, in run_on_record
    results.knowncluster = run_knownclusterblast_on_record(record, options)
  File "/prj/nanopore/bin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/modules/clusterblast/known.py", line 90, in run_knownclusterblast_on_record
    return perform_knownclusterblast(options, record, clusters, proteins)
  File "/prj/nanopore/bin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/modules/clusterblast/known.py", line 115, in perform_knownclusterblast
    write_raw_clusterblastoutput(options.output_dir, blastoutput,
  File "/prj/nanopore/bin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/modules/clusterblast/core.py", line 534, in write_raw_clusterblastoutput
    handle.write(blast_output)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u03b1' in position 49712: ordinal not in range(256)

-- Error message 2
[01_Pseudomonas_syringae_DSM_1241.gbk.gz](https://github.com/antismash/antismash/files/8956829/01_Pseudomonas_syringae_DSM_1241.gbk.gz)
[04_Janthinobacterium_agaricidamnosum_DSM9628.gbk.gz](https://github.com/antismash/antismash/files/8956830/04_Janthinobacterium_agaricidamnosum_DSM9628.gbk.gz)
 --
Traceback (most recent call last):
  File "/prj/nanopore/bin/miniconda3/envs/antismash/bin/antismash", line 8, in <module>
    sys.exit(entrypoint())
  File "/prj/nanopore/bin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/__main__.py", line 125, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/prj/nanopore/bin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/__main__.py", line 113, in main
    antismash.run_antismash(sequence, options)
  File "/prj/nanopore/bin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/main.py", line 673, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/prj/nanopore/bin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/main.py", line 748, in _run_antismash
    write_outputs(results, options)
  File "/prj/nanopore/bin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/main.py", line 451, in write_outputs
    html.write(results.records, module_results_per_record, options, get_all_modules())
  File "/prj/nanopore/bin/miniconda3/envs/antismash/lib/python3.8/site-packages/antismash/outputs/html/__init__.py", line 109, in write
    result_file.write(content)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u03b2' in position 131713: ordinal not in range(256)

**System (please complete the following information):**
 - OS: Ubuntu
 - Kernel: 5.4.0-72-generic
 - Architecture: x86_64

**Comment by kblin** [comment]
Interesting. I wonder why this is trying to even use latin-1 as the codec and not utf-8.

**Comment by crueckert-cebitec** [comment]
I actually found the "solution" in Issue #272: 

export LANG=C.UTF-8

does the trick. No idea why that is not set correctly. Most likely a local problem.
