### ISSUE TITLE
Problem with download-antismash-database on TIGRFam database

### ISSUE THREAD

**Issue by pietermonsieurs** [antismash/antismash#462]
Hi, I was trying to do a local installation of the antismash software via a conda environment. However, when downloading the databases, I ran into troubles when downloading the TIGRfam database, due to an SSL certificat error. Do you have any idea to circumvent this issue? Can I download this via another way, and copy to the correct antismash directory? 

Thanks in advance!
Kind regards,
Pieter

./download-antismash-databases --database-dir ../databases/
Creating checksum of Pfam-A.hmm
PFAM file present and ok for version 32.0
Downloading Resfam database
Downloading Resfams.hmm.gz: 100.00% downloaded.
Creating checksum of Resfams.hmm.gz
Extraction of Resfams.hmm.gz finished successfully.
Ensuring all cutoffs are present
Downloading TIGRFam database
Traceback (most recent call last):
  File "/apps/antwerpen/x86_64/centos8/intel-psxe/2020.02/intelpython3/lib/python3.7/urllib/request.py", line 1319, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/apps/antwerpen/x86_64/centos8/intel-psxe/2020.02/intelpython3/lib/python3.7/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/apps/antwerpen/x86_64/centos8/intel-psxe/2020.02/intelpython3/lib/python3.7/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/apps/antwerpen/x86_64/centos8/intel-psxe/2020.02/intelpython3/lib/python3.7/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/apps/antwerpen/x86_64/centos8/intel-psxe/2020.02/intelpython3/lib/python3.7/http/client.py", line 1028, in _send_output
    self.send(msg)
  File "/apps/antwerpen/x86_64/centos8/intel-psxe/2020.02/intelpython3/lib/python3.7/http/client.py", line 968, in send
    self.connect()
  File "/apps/antwerpen/x86_64/centos8/intel-psxe/2020.02/intelpython3/lib/python3.7/http/client.py", line 1432, in connect
    server_hostname=server_hostname)
  File "/apps/antwerpen/x86_64/centos8/intel-psxe/2020.02/intelpython3/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/apps/antwerpen/x86_64/centos8/intel-psxe/2020.02/intelpython3/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/apps/antwerpen/x86_64/centos8/intel-psxe/2020.02/intelpython3/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/user/antwerpen/205/vsc20587/scratch/software/antismash-6.0.0/lib/python3.7/site-packages/antismash/download_databases.py", line 90, in download_file
    req = request.urlopen(url)
  File "/apps/antwerpen/x86_64/centos8/intel-psxe/2020.02/intelpython3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/apps/antwerpen/x86_64/centos8/intel-psxe/2020.02/intelpython3/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/apps/antwerpen/x86_64/centos8/intel-psxe/2020.02/intelpython3/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/apps/antwerpen/x86_64/centos8/intel-psxe/2020.02/intelpython3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/apps/antwerpen/x86_64/centos8/intel-psxe/2020.02/intelpython3/lib/python3.7/urllib/request.py", line 1362, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/apps/antwerpen/x86_64/centos8/intel-psxe/2020.02/intelpython3/lib/python3.7/urllib/request.py", line 1321, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./download-antismash-databases", line 8, in <module>
    sys.exit(_main())
  File "/user/antwerpen/205/vsc20587/scratch/software/antismash-6.0.0/lib/python3.7/site-packages/antismash/download_databases.py", line 397, in _main
    download(args)
  File "/user/antwerpen/205/vsc20587/scratch/software/antismash-6.0.0/lib/python3.7/site-packages/antismash/download_databases.py", line 371, in download
    download_tigrfam(args.database_dir)
  File "/user/antwerpen/205/vsc20587/scratch/software/antismash-6.0.0/lib/python3.7/site-packages/antismash/download_databases.py", line 314, in download_tigrfam
    download_if_not_present(TIGRFAM_URL, archive_filename, TIGRFAM_ARCHIVE_CHECKSUM)
  File "/user/antwerpen/205/vsc20587/scratch/software/antismash-6.0.0/lib/python3.7/site-packages/antismash/download_databases.py", line 215, in download_if_not_present
    download_file(url, filename)
  File "/user/antwerpen/205/vsc20587/scratch/software/antismash-6.0.0/lib/python3.7/site-packages/antismash/download_databases.py", line 92, in download_file
    raise DownloadError("ERROR: File not found on server.\nPlease check your internet connection.")
antismash.download_databases.DownloadError: ERROR: File not found on server.
Please check your internet connection.

**Comment by SJShaw** [comment]
The current certificate for `dl.secondarymetabolites.org`, which is where the download script tries to fetch TIGRFam from expires on the 29th of August 2022, and we're not quite there yet.

This could be a few things, but they'll all be related to your system or network and that will probably also prevent you from using any workaround:
- check your system time is correct
- check if the request is going out through some kind of proxy that's interrupting the SSL process
- check you can properly access the file via the command line or browser (on that same system), whichever is easier, (https://dl.secondarymetabolites.org/releases/tigrfam/TIGRFam.hmm.gz, contained in the `download_databases.py` script)

As for workarounds, manually download it, extract it to `../databases/tigrfam/TIGRFam.hmm`, and then that `download_if_not_present` mentioned in the stack trace will use just use it instead of trying to download it again.

You can see all the download links in the [script itself](https://github.com/antismash/antismash/blob/6-0-stable/antismash/download_databases.py). You'll probably need it if you can manually download the first, since there's other databases on the same host.

**Comment by pietermonsieurs** [comment]
Great, thanks for the suggestions. 
I assume the download issue is related to the fact that I am working on a supercomputer system. 
I will try downloading  the TIGRFamm manually in that case. The strange thing is that I don't have issues downloading the PFAM or the Resfam database via this download script. Still to see how it behaves with the ClusterBlast database...

**Comment by pietermonsieurs** [comment]
OK, great! Downloading them manually did the trick. Thanks for the help!
