### ISSUE TITLE
error 'cannot import name 'Markup' from 'jinja2' while using  download-antismash-databases

### ISSUE THREAD

**Issue by jehaab** [antismash/antismash#463]
Hi,

I have followed the steps to install anti-smash (system is Linux) and created a virtual environment (python 3.10).

The following steps ran smoothly:
wget https://dl.secondarymetabolites.org/releases/6.0.0/antismash-6.0.0.tar.gz
tar -zxf antismash-6.0.0.tar.gz
pip install ./antismash-6.0.0

However, 
download-antismash-databases returns the following error:

> Traceback (most recent call last):
>   File "/project/6007483/software/env_antiSMASH/bin/download-antismash-databases", line 5, in <module>
>     from antismash.download_databases import _main
>   File "/project/6007483/software/env_antiSMASH/lib/python3.10/site-packages/antismash/__init__.py", line 12, in <module>
>     from antismash.main import run_antismash, get_detection_modules, \
>   File "/project/6007483/software/env_antiSMASH/lib/python3.10/site-packages/antismash/main.py", line 35, in <module>
>     from antismash.detection import (cassis,
>   File "/project/6007483/software/env_antiSMASH/lib/python3.10/site-packages/antismash/detection/nrps_pks_domains/__init__.py", line 15, in <module>
>     from .domain_drawing import generate_html, generate_js_domains, will_handle
>   File "/project/6007483/software/env_antiSMASH/lib/python3.10/site-packages/antismash/detection/nrps_pks_domains/domain_drawing.py", line 16, in <module>
>     from antismash.common.html_renderer import FileTemplate, HTMLSections
>   File "/project/6007483/software/env_antiSMASH/lib/python3.10/site-packages/antismash/common/html_renderer.py", line 12, in <module>
>     from jinja2 import Markup
> ImportError: cannot import name 'Markup' from 'jinja2' (/project/6007483/software/env_antiSMASH/lib/python3.10/site-packages/jinja2/__init__.py)
> 

I tried to use jinja2 3.0.0, it starts running but then another error comes up,

> Creating checksum of Pfam-A.hmm
PFAM file present and ok for version 32.0
Downloading Resfam database
Downloading Resfams.hmm.gz: 100.00% downloaded.
Creating checksum of Resfams.hmm.gz
Extraction of Resfams.hmm.gz finished successfully.
Traceback (most recent call last):
  File "/project/6007483/software/env_antiSMASH/bin/download-antismash-databases", line 8, in <module>
    sys.exit(_main())
  File "/project/6007483/software/env_antiSMASH/lib/python3.10/site-packages/antismash/download_databases.py", line 397, in _main
    download(args)
  File "/project/6007483/software/env_antiSMASH/lib/python3.10/site-packages/antismash/download_databases.py", line 369, in download
    download_resfam(args.database_dir)
  File "/project/6007483/software/env_antiSMASH/lib/python3.10/site-packages/antismash/download_databases.py", line 261, in download_resfam
    converted = execute(["hmmconvert", filename])
  File "/project/6007483/software/env_antiSMASH/lib/python3.10/site-packages/antismash/common/subprocessing/base.py", line 86, in execute
    proc = Popen(commands, stdin=stdin_redir, stdout=stdout, stderr=stderr)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hmmconvert'

How would be able to fix this problem and finish installing antiSMASH.

Thank you

**Comment by jehaab** [comment]
Thank you
