### ISSUE TITLE
Traceback (most recent call last) and issues running antiSMASH

### ISSUE THREAD

**Issue by aminabradley** [antismash/antismash#472]
**Describe the bug**
I have tried installing antiSmash on my local computer multiple times and I keep running into different issues. 

I install the antismash-6-1-0 with the followed condes:
$ conda create -n antismash
$ conda activate antismash

$ conda install -y diamond=0.8.36
$ conda install -y fasttree=2.1.9
$ conda install -y glimmerhmm=3.0.4
$ conda install -y hmmer2
$ conda install -y hmmer=3.1b2
$ conda install -y meme=4.11.2
$ conda install -y muscle=3.8.1551
$ conda install -y blast=2.2.31
$ conda install -y prodigal=2.6.3
$ conda install -y java-jdk
$ conda install -y python
$ wget https://dl.secondarymetabolites.org/releases/6.1.0/antismash-6.1.0.tar.gz
$ tar -zxf antismash-6.1.0.tar.gz
$ pip install ./antismash-6.1.0.

$ download-antismash-databases

When I try to install blast and meme I see

Verifying transaction: failed
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Error Report <<<<<<<<<<<<<<<<<<<<<
 Traceback (most recent call last):
      File "/mnt/c/Users/bradla/lib/python3.9/site-packages/conda/exceptions.py", line 1125, in __call__
        return func(*args, **kwargs)
      File "/mnt/c/Users/bradla/lib/python3.9/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/mnt/c/Users/bradla/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
        return getattr(module, func_name)(args, parser)
      File "/mnt/c/Users/bradla/lib/python3.9/site-packages/conda/notices/core.py", line 72, in wrapper
        return_value = func(*args, **kwargs)
      File "/mnt/c/Users/bradla/lib/python3.9/site-packages/conda/cli/main_install.py", line 22, in execute
        install(args, parser, 'install')
      File "/mnt/c/Users/bradla/lib/python3.9/site-packages/conda/cli/install.py", line 324, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/mnt/c/Users/bradla/lib/python3.9/site-packages/conda/cli/install.py", line 353, in handle_txn
        unlink_link_transaction.execute()
      File "/mnt/c/Users/bradla/lib/python3.9/site-packages/conda/core/link.py", line 277, in execute
        self.verify()
      File "/mnt/c/Users/bradla/lib/python3.9/site-packages/conda/common/io.py", line 86, in decorated
        return f(*args, **kwds)
      File "/mnt/c/Users/bradla/lib/python3.9/site-packages/conda/core/link.py", line 238, in verify
        exceptions = self._verify(self.prefix_setups, self.prefix_action_groups)
      File "/mnt/c/Users/bradla/lib/python3.9/site-packages/conda/core/link.py", line 622, in _verify
        for exc in self.verify_executor.map(UnlinkLinkTransaction._verify_individual_level,
      File "/mnt/c/Users/bradla/lib/python3.9/site-packages/conda/common/io.py", line 520, in map
        yield func(thing)
      File "/mnt/c/Users/bradla/lib/python3.9/site-packages/conda/core/link.py", line 443, in _verify_individual_level
        error_result = axn.verify()
      File "/mnt/c/Users/bradla/lib/python3.9/site-packages/conda/core/path_actions.py", line 319, in verify
        source_size_in_bytes = getsize(self.source_full_path)
      File "/mnt/c/Users/bradla/lib/python3.9/genericpath.py", line 50, in getsize
        return os.stat(filename).st_size
OSError: [Errno 40] Too many levels of symbolic links: '/mnt/c/Users/bradla/pkgs/ncurses-6.3-h27087fc_1/share/terminfo/N/NCR260VT300WPP

I've also tried updating conda before trying the installation as well as:
$ conda install -c bioconda meme

and I continue to run into issues with different packages. If anyone knows has any advice on how I may be able to fix these issues please let me know

**Comment by SJShaw** [comment]
Unfortunately this has nothing to do with antiSMASH itself. You've almost certainly got some symlinks forming a self-referential loop somewhere in what looks like a WSL setup.

I'd use the home directory of your WSL user completely independently from your Windows user directory (`/mnt/c/Users/...`), install conda fresh inside the virtual machine and then all the relevant dependencies.

The conda repository might be a better place to ask, as they can probably help more with where extra symlinks might be created.
