### ISSUE TITLE
RuntimeError: unexpected output from muscle: /home/mestiri/anaconda3/envs/antismash/bin/muscle, check path

### ISSUE THREAD

**Issue by MesYosra** [antismash/antismash#582]
Hello,
I have installed antismash with bioconada:

conda create -n antismash
conda activate antismash
conda install hmmer2 hmmer diamond fasttree prodigal blast muscle glimmerhmm

Then when I run :
antismash /home/mestiri/dossierTest/UK001/UK001.fai 

I have this error: 

Traceback (most recent call last):
  File "/home/mestiri/.local/bin/antismash", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/mestiri/.local/lib/python3.10/site-packages/antismash/__main__.py", line 129, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/home/mestiri/.local/lib/python3.10/site-packages/antismash/__main__.py", line 118, in main
    antismash.run_antismash(sequence, options)
  File "/home/mestiri/.local/lib/python3.10/site-packages/antismash/main.py", line 630, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/home/mestiri/.local/lib/python3.10/site-packages/antismash/main.py", line 637, in _run_antismash
    _log_found_executables(options)
  File "/home/mestiri/.local/lib/python3.10/site-packages/antismash/main.py", line 736, in _log_found_executables
    version = " ({})".format(version_getter())  # pylint: disable=not-callable
  File "/home/mestiri/.local/lib/python3.10/site-packages/antismash/common/subprocessing/muscle.py", line 55, in run_muscle_version
    raise RuntimeError(msg % muscle)
RuntimeError: unexpected output from muscle: /home/mestiri/anaconda3/envs/antismash/bin/muscle, check path

I versify the path and it exists.

when I run this command to get the version of muscle:
home/mestiri/anaconda3/envs/antismash/bin/muscle -version

I get this:
muscle 5.1.linux64 []
Built Feb 24 2022 03:16:15

I don't know why it crashes I need help please. Thank you

**Comment by SJShaw** [comment]
MUSCLE 5 is not supported, they removed the profile-profile mode in version 5 and that's all antiSMASH was using it for.

Either install 3.8 or use the current beta of antiSMASH, which has completely removed MUSCLE as a dependency.
