### ISSUE TITLE
Conda Installation issue

### ISSUE THREAD

**Issue by SheikGeomicro** [antismash/antismash#606]
Hello, 

I'm trying to install the latest version of antismash using Conda. I'm getting an insufficient memory error that kills the installation. I'm installing it on our supercomputing cluster and have several Tb of disk space available. I'm out of ideas on what's going on! Our cluster uses CentOS.  

ERROR conda.core.link:_execute(699): An error occurred while installing package 'bioconda::antismash-6.1.1-pyhdfd78af_0'.
Rolling back transaction: done
class: LinkError
message:
post-link script failed for package bioconda::antismash-6.1.1-pyhdfd78af_0
location of failed script: ~/anaconda3/envs/antismash/bin/.antismash-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: Creating checksum of Pfam-A.hmm
PFAM file present and ok for version 34.0
Downloading Resfam database
Downloading Resfams.hmm.gz: 100.00% downloaded.
Creating checksum of Resfams.hmm.gz
Extraction of Resfams.hmm.gz finished successfully.
Ensuring all cutoffs are present
Creating checksum of TIGRFam.hmm
TIGRFam database present and checked
Downloading ClusterBlast database.

stderr: Traceback (most recent call last):
  File "~/anaconda3/envs/antismash/bin/download-antismash-databases", line 10, in <module>
    sys.exit(_main())
  File "~/anaconda3/envs/antismash/lib/python3.9/site-packages/antismash/download_databases.py", line 397, in _main
    download(args)
  File "~/anaconda3/envs/antismash/lib/python3.9/site-packages/antismash/download_databases.py", line 372, in download
    download_clusterblast(args.database_dir)
  File "~/cssheik/anaconda3/envs/antismash/lib/python3.9/site-packages/antismash/download_databases.py", line 330, in download_clusterblast
    check_diskspace(CLUSTERBLAST_URL)
  File "~/anaconda3/envs/antismash/lib/python3.9/site-packages/antismash/download_databases.py", line 82, in check_diskspace
    raise DownloadError(
antismash.download_databases.DownloadError: ERROR: Insufficient disk space available (required: 539743196, free: 520273920).

return code: 1

**Comment by SJShaw** [comment]
Closing this as stale.
