### ISSUE TITLE
from numpy.core._multiarray_umath import

### ISSUE THREAD

**Issue by qianxin-kxy** [antismash/antismash#610]
### I finally installed it using the following method
(antismash) [kongxy@localhost ~]$ conda install hmmer2 hmmer diamond fasttree prodigal blast muscle glimmerhmm
(antismash) [kongxy@localhost ~]$ conda install meme=4.11.2
(antismash) [kongxy@localhost ~]$ cd data1  
(antismash) [kongxy@localhost data1]$ wget https://dl.secondarymetabolites.org/releases/5.2.0/antismash-5.2.0.tar.gz   
(antismash) [kongxy@localhost data1]$ tar -zxf antismash-5.2.0.tar.gz                                                                        
(antismash) [kongxy@localhost data1]$ pip install ./antismash-5.2.0  
(antismash) [kongxy@localhost data1]$ download-antismash-databases
(antismash) [kongxy@localhost data1]$ pip install jinja2==2.9
(antismash) [kongxy@localhost data1]$ download-antismash-databases
(antismash) [kongxy@localhost data1]$ pip install markupsafe==2.0.0
(antismash) [kongxy@localhost data1]$ download-antismash-databases 
(antismash) [kongxy@localhost data1]$ conda install diamond=2.0.9 --repodata-fn repodata.json
(antismash) [kongxy@localhost data1]$ conda install muscle=3.8.31
(antismash) [kongxy@localhost data1]$ antismash --check-prereqs
All prerequisites satisfied

**Running with the following code, encountered a bug**
(antismash) [kongxy@localhost 20230509gbk]$ antismash 4751.gbk
ERROR    09/06 11:07:42   Parsing 'bl_2012_ST381_4751.gbk' failed: Did not recognise the LOCUS line layout:
LOCUS       NODE_2_length_354722_cov_51.4144354722 bp   DNA linear

ERROR    09/06 11:07:42   Did not recognise the LOCUS line layout:
LOCUS       NODE_2_length_354722_cov_51.4144354722 bp   DNA linear
**Attempted to run with different code, but also encountered a bug**
(antismash) [kongxy@localhost 20230509gbk]$ antismash --cb-general --cb-knownclusters --cb-subclusters --asf --pfam2go --smcog-trees --genefinding-gff3 4751.gff 4751.fasta
WARNING  09/06 11:14:25   Fasta header too long: renamed "NODE_1_length_364427_cov_54.2144" to "c00001_NODE_1_.."
WARNING  09/06 11:14:25   Fasta header too long: renamed "NODE_2_length_354722_cov_51.4144" to "c00002_NODE_2_.."
……………………
OpenBLAS blas_thread_init: pthread_create failed for thread 62 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 63 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
Process ForkPoolWorker-265:
Traceback (most recent call last):
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/smcog_trees/trees.py", line 68, in smcog_tree_analysis
    draw_tree(input_number, output_dir, gene_id)
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/smcog_trees/trees.py", line 165, in draw_tree
    fig.savefig(os.path.join(output_dir, tag + '.png'), bbox_inches='tight')
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/matplotlib/figure.py", line 3058, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2300, in print_figure
    renderer, bbox_extra_artists=bbox_extra_artists)
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/matplotlib/figure.py", line 1714, in get_tightbbox
    _bbox = TransformedBbox(_bbox, self.dpi_scale_trans.inverted())
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/matplotlib/transforms.py", line 1890, in inverted
    self._inverted = Affine2D(inv(mtx), shorthand_name=shorthand_name)
  File "<__array_function__ internals>", line 6, in inv
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 545, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
KeyboardInterrupt
**Attempted to fix the bug, but was unsuccessful and encountered a new bug**
(antismash) [kongxy@localhost 20230509gbk]$ wget https://dl.secondarymetabolites.org/testing/balh.embl
(antismash) [kongxy@localhost 20230509gbk]$ antismash -d --cpus 2 --smcog-trees balh.embl

OpenBLAS blas_thread_init: pthread_create failed for thread 53 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 54 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 55 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 56 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 57 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 58 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 59 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 60 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 61 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 62 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 63 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
Traceback (most recent call last):
  File "/home/kongxy/miniconda3/envs/antismash/bin/antismash", line 5, in <module>
    from antismash.__main__ import entrypoint
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 35, in <module>
    from antismash.detection import (cassis,
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/clusterfinder_probabilistic/__init__.py", line 16, in <module>
    from .probabilistic import find_probabilistic_clusters, get_pfam_probabilities
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/clusterfinder_probabilistic/probabilistic.py", line 13, in <module>
    import numpy as np
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/numpy/__init__.py", line 150, in <module>
    from . import core
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
KeyboardInterrupt
段错误 (core dumped)
**Regardless of the new bug, try to run it, but cannot overcome it, and I really don't know what to do next**
(antismash) [kongxy@localhost 20230509gbk]$ antismash --cb-general --cb-knownclusters --cb-subclusters --asf --pfam2go --smcog-trees --genefinding-gff3 4751.gff 4751.fasta
OpenBLAS blas_thread_init: pthread_create failed for thread 53 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 54 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 55 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 56 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 57 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 58 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 59 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 60 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 61 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 62 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
OpenBLAS blas_thread_init: pthread_create failed for thread 63 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 10240 max
Traceback (most recent call last):
  File "/home/kongxy/miniconda3/envs/antismash/bin/antismash", line 5, in <module>
    from antismash.__main__ import entrypoint
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/__init__.py", line 12, in <module>
    from antismash.main import run_antismash, get_detection_modules, \
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 35, in <module>
    from antismash.detection import (cassis,
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/clusterfinder_probabilistic/__init__.py", line 16, in <module>
    from .probabilistic import find_probabilistic_clusters, get_pfam_probabilities
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/detection/clusterfinder_probabilistic/probabilistic.py", line 13, in <module>
    import numpy as np
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/numpy/__init__.py", line 150, in <module>
    from . import core
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/kongxy/miniconda3/envs/antismash/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
KeyboardInterrupt
段错误 (core dumped)

**Comment by SJShaw** [comment]
That's an issue in the numpy package. You can confirm that by just trying `import numpy as np` in python (outside of antiSMASH).
As for fixing it, you might be able to rebuild it for your system, since it has compiled portions and you maybe have installed an incompatible version. Another option might be trying to use a more recent version of numpy (so `pip install --upgrade numpy`).

If none of those fix it, you'll need to create an issue with the numpy maintainers.

**Comment by qianxin-kxy** [comment]
Thank you for your reply. I tried this,but it didn't work:
$ pip install --upgrade numpy

I plan to uninstall the software and install it again to see whether it would be fine.
In addition, I would like to ask, although there are errors reported above, there are still results after analyzing the genome of the strain. Will the above errors have an impact on the results?Or perhaps the result is also credible and usable

**Comment by SJShaw** [comment]
If a module has generated some results _and_ it is not the module that caused the crash, the results are likely reliable.
However, since your crash is in clusterfinder, then no analysis modules will have run, only detection modules, which means that things are a bit risky to trust.
