### ISSUE TITLE
RuntimeError: diamond failed to run: blastp -> d, or a system-imposed limit on the number of threads was encountered.

### ISSUE THREAD

**Issue by qianxin-kxy** [antismash/antismash#615]
### Hello！ I have a new problem running the code below
**I saw that someone had this issue before, and the problem was solved by changing mac to Ubuntu system or diamond to version 0.9.24. However, I am using the linux system, and I replaced diamond=0.9.36 with diamond=0.9.24, but the problem still exists. I don’t know what to do?**
**my antiSMASH version is  6.1.1**

(antismash) [kxy@zju antismash]$ antismash --genefinding-tool prodigal --cb-general --cb-knownclusters --cb-subclusters --asf --pfam2go --smcog-trees 4751.gbk --output-dir 4751  
WARNING  13/06 00:58:10   Fasta header too long: renamed "NODE_53_length_1013_cov_" to "c00052_NODE_53.."
Traceback (most recent call last):
  File "/data/users/kxy/miniconda3/envs/antismash/bin/antismash", line 10, in <module>
    sys.exit(entrypoint())
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/__main__.py", line 125, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/__main__.py", line 113, in main
    antismash.run_antismash(sequence, options)
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 674, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 734, in _run_antismash
    analysis_timings = analyse_record(record, options, get_analysis_modules(), module_results)
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 299, in analyse_record
    run_module(record, module, options, previous_result, timings)
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/main.py", line 271, in run_module
    results = module.run_on_record(record, results, options)
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/__init__.py", line 154, in run_on_record
    results.general = perform_clusterblast(options, record, clusters, proteins)
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/clusterblast.py", line 42, in perform_clusterblast
    blastoutput = run_diamond_on_all_regions(regions, database)
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/modules/clusterblast/core.py", line 82, in run_diamond_on_all_regions
    stdout = subprocessing.run_diamond_search(temp_file.name, database, mode="blastp", opts=extra_args)
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/subprocessing/diamond.py", line 71, in run_diamond_search
    return run_diamond(mode, args).stdout
  File "/data/users/kxy/miniconda3/envs/antismash/lib/python3.7/site-packages/antismash/common/subprocessing/diamond.py", line 45, in run_diamond
    raise RuntimeError("diamond failed to run: %s -> %s" % (subcommand, result.stderr[-100:]))
RuntimeError: diamond failed to run: blastp -> d, or a system-imposed limit on the number of threads was encountered.

**Comment by SJShaw** [comment]
Diamond is failing to create as many threads as requested. This could be a memory problem or a system configuration problem. When not specifying the maximum number of threads to antiSMASH with `--cpus N`, it will by default use all available cores. If you have many cores, that might cause more of a memory issue and thus run out of resources or hit the limits.

We have tested on machines with 256 cores before and haven't hit this, so we need more information about the machine in question in order to work out ways to avoid this.

**Comment by qianxin-kxy** [comment]
> Diamond is failing to create as many threads as requested. This could be a memory problem or a system configuration problem. When not specifying the maximum number of threads to antiSMASH with `--cpus N`, it will by default use all available cores. If you have many cores, that might cause more of a memory issue and thus run out of resources or hit the limits.
> 
> We have tested on machines with 256 cores before and haven't hit this, so we need more information about the machine in question in order to work out ways to avoid this.

**Thank you for responding!
I query through the following code and know that the linux system server used contains 3 cpus, 20 cores, and 160 threads.**

(base) [kxy@zju ~]$ grep 'processor' /proc/cpuinfo | sort -u | wc -l
160
(base) [kxy@zju ~]$ grep 'physical id' /proc/cpuinfo | sort -u
physical id	: 0
physical id	: 1
physical id	: 2
physical id	: 3
(base) [kxy@zju ~]$ grep 'core id' /proc/cpuinfo | sort -u | wc -l
20

**Besides, theose codes is run in a special virtual environment created by conda：$ antismash --genefinding-tool prodigal --cb-general --cb-knownclusters --cb-subclusters --asf --pfam2go --smcog-trees 4751.gbk --output-dir 4751.I don't know if this information is kind enough for your help me to figure out what's wrong?**

**Comment by SJShaw** [comment]
Specify a reasonable number of threads to use with `--cpus 16`. Attempting to use all 160 virtual cores is likely the cause of your problem and even if it were to work, would likely make diamond run slower instead of faster.
