### ISSUE TITLE
antismash runtime error hmmscan

### ISSUE THREAD

**Issue by CK9699** [antismash/antismash#623]
I have installed antismash 7.0.0. Regardless of the genome used and regardless if the input is a fasta or genbank file this error for hmmscan occurs always on the first CDS listed in the genbank file or the first CDS found if using a fasta file:

antismash --output-dir  /beegfs/ws/0/pada358b-conda/working/results --fullhmmer --pfam2go --cc-mibig /beegfs/ws/0/pada358b-conda/working/genomes/Nostoc_sp_40_5_MAG.gbff
 
INFO     20/07 08:28:56   antiSMASH version: 7.0.0
INFO     20/07 08:28:56   diamond using executable: /beegfs/ws/0/pada358b-conda/envs/antismash/bin/diamond (2.0.15)
INFO     20/07 08:28:56   hmmpfam2 using executable: /beegfs/ws/0/pada358b-conda/envs/antismash/bin/hmmpfam2 (2.3.2)
INFO     20/07 08:28:56   fasttree using executable: /beegfs/ws/0/pada358b-conda/envs/antismash/bin/fasttree
INFO     20/07 08:28:56   hmmsearch using executable: /beegfs/ws/0/pada358b-conda/envs/antismash/bin/hmmsearch (3.3.2)
INFO     20/07 08:28:56   hmmpress using executable: /beegfs/ws/0/pada358b-conda/envs/antismash/bin/hmmpress (3.3.2)
INFO     20/07 08:28:56   hmmscan using executable: /beegfs/ws/0/pada358b-conda/envs/antismash/bin/hmmscan (3.3.2)
INFO     20/07 08:28:56   meme using executable: /beegfs/ws/0/pada358b-conda/envs/antismash/bin/meme (4.11.2)
INFO     20/07 08:28:56   fimo using executable: /beegfs/ws/0/pada358b-conda/envs/antismash/bin/fimo (4.11.2)
INFO     20/07 08:28:56   glimmerhmm using executable: /beegfs/ws/0/pada358b-conda/envs/antismash/bin/glimmerhmm
INFO     20/07 08:28:56   prodigal using executable: /beegfs/ws/0/pada358b-conda/envs/antismash/bin/prodigal (V2.6.3)
INFO     20/07 08:28:57   blastp using executable: /beegfs/ws/0/pada358b-conda/envs/antismash/bin/blastp (2.14.0+)
INFO     20/07 08:28:57   makeblastdb using executable: /beegfs/ws/0/pada358b-conda/envs/antismash/bin/makeblastdb (2.14.0+)
INFO     20/07 08:28:57   Parsing input sequence '/beegfs/ws/0/pada358b-conda/working/genomes/Nostoc_sp_40_5_MAG.gbff'
INFO     20/07 08:29:04   Analysing record: contig_1
INFO     20/07 08:29:04   Running antismash.detection.full_hmmer
INFO     20/07 08:29:04   Running whole-genome PFAM search
Traceback (most recent call last):
  File "/beegfs/ws/0/pada358b-conda/envs/antismash/bin/antismash", line 8, in <module>
    sys.exit(entrypoint())
  File "/beegfs/ws/0/pada358b-conda/envs/antismash/lib/python3.10/site-packages/antismash/__main__.py", line 124, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/beegfs/ws/0/pada358b-conda/envs/antismash/lib/python3.10/site-packages/antismash/__main__.py", line 112, in main
    antismash.run_antismash(sequence, options)
  File "/beegfs/ws/0/pada358b-conda/envs/antismash/lib/python3.10/site-packages/antismash/main.py", line 675, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/beegfs/ws/0/pada358b-conda/envs/antismash/lib/python3.10/site-packages/antismash/main.py", line 735, in _run_antismash
    timings = run_detection(record, options, module_results)
  File "/beegfs/ws/0/pada358b-conda/envs/antismash/lib/python3.10/site-packages/antismash/main.py", line 190, in run_detection
    run_module(record, module, options, module_results, timings)
  File "/beegfs/ws/0/pada358b-conda/envs/antismash/lib/python3.10/site-packages/antismash/main.py", line 274, in run_module
    results = module.run_on_record(record, results, options)
  File "/beegfs/ws/0/pada358b-conda/envs/antismash/lib/python3.10/site-packages/antismash/detection/full_hmmer/__init__.py", line 112, in run_on_record
    return hmmer.run_hmmer(record, record.get_cds_features(), MAX_EVALUE, MIN_SCORE, database, "fullhmmer")
  File "/beegfs/ws/0/pada358b-conda/envs/antismash/lib/python3.10/site-packages/antismash/common/hmmer.py", line 269, in run_hmmer
    hmmscan_results = subprocessing.run_hmmscan(database, query_sequence, opts=opts)
  File "/beegfs/ws/0/pada358b-conda/envs/antismash/lib/python3.10/site-packages/antismash/common/subprocessing/hmmscan.py", line 59, in run_hmmscan
    raise RuntimeError("".join([
RuntimeError: hmmscan returned -24: '# hmmscan :: search sequence(s) against a profile database' while scanning '>GNKDGJ_00005\nMNEFEFEDWCRQRQLATNTIDLIALLRKSPPSRRVQGRTKNVCGVYPSSKMGVTIQFESHTVELWAIYLMEHDPKVLEFYDQPPPF'...

**Comment by CK9699** [comment]
Maybe the current hmmer version is the problem? We already tried to change the version but without success. It says conda cannot find the package in the current channels.

**Comment by kblin** [comment]
this looks like an error in hmmscan. Do you get this error on all inputs?

**Comment by kblin** [comment]
Digging a bit into the hmmer source code, I'm pretty certain that hmmscan should only return 1 on any input error. Negative return codes are system-wide signals, and signal 24 turns out to be `SIGXCPU` which means "CPU time limit exceeded".

This is completely outside of antiSMASH's control. If you're running in a cluster context, you might need to increase the CPU allocation to your batch job.
