### ISSUE TITLE
blastp -> ['Error: The sequences are expected to be proteins but only contain DNA letters.

### ISSUE THREAD

**Issue by 123xiaochen** [antismash/antismash#683]
Hi , There was an error when I ran antismash7.0 locally, but I checked the relevant error information and didn't find a solution. The error shows as follows.

Analysis command:
antismash --cb-knownclusters --cb-general --pfam2go  --genefinding-tool  prodigal --output-dir ./ncbi_bacteria_refseq_completeGCF_003952445.1_NZ_CP034446.1.region007 ncbi_bacteria_refseq_completeGCF_003952445.1_NZ_CP034446.1.region007.finnal.gbk 

error message：
Traceback (most recent call last):
  File "/Users/lab_wang/miniconda3/envs/antismash7.0/bin/antismash", line 8, in <module>
    sys.exit(entrypoint())
  File "/Users/lab_wang/miniconda3/envs/antismash7.0/lib/python3.9/site-packages/antismash/__main__.py", line 124, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/Users/lab_wang/miniconda3/envs/antismash7.0/lib/python3.9/site-packages/antismash/__main__.py", line 112, in main
    antismash.run_antismash(sequence, options)
  File "/Users/lab_wang/miniconda3/envs/antismash7.0/lib/python3.9/site-packages/antismash/main.py", line 675, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/Users/lab_wang/miniconda3/envs/antismash7.0/lib/python3.9/site-packages/antismash/main.py", line 739, in _run_antismash
    analysis_timings = analyse_record(record, options, get_analysis_modules(), module_results)
  File "/Users/lab_wang/miniconda3/envs/antismash7.0/lib/python3.9/site-packages/antismash/main.py", line 302, in analyse_record
    run_module(record, module, options, previous_result, timings)
  File "/Users/lab_wang/miniconda3/envs/antismash7.0/lib/python3.9/site-packages/antismash/main.py", line 274, in run_module
    results = module.run_on_record(record, results, options)
  File "/Users/lab_wang/miniconda3/envs/antismash7.0/lib/python3.9/site-packages/antismash/modules/clusterblast/__init__.py", line 153, in run_on_record
    results.general = perform_clusterblast(options, record, clusters, proteins)
  File "/Users/lab_wang/miniconda3/envs/antismash7.0/lib/python3.9/site-packages/antismash/modules/clusterblast/clusterblast.py", line 42, in perform_clusterblast
    blastoutput = run_diamond_on_all_regions(regions, database)
  File "/Users/lab_wang/miniconda3/envs/antismash7.0/lib/python3.9/site-packages/antismash/modules/clusterblast/core.py", line 85, in run_diamond_on_all_regions
    stdout = subprocessing.run_diamond_search(temp_file.name, database, mode="blastp", opts=extra_args)
  File "/Users/lab_wang/miniconda3/envs/antismash7.0/lib/python3.9/site-packages/antismash/common/subprocessing/diamond.py", line 74, in run_diamond_search
    return run_diamond(mode, args).stdout
  File "/Users/lab_wang/miniconda3/envs/antismash7.0/lib/python3.9/site-packages/antismash/common/subprocessing/diamond.py", line 48, in run_diamond
    raise RuntimeError(message)
RuntimeError: diamond failed to run: blastp -> ['Error: The sequences are expected to be proteins but only contain DNA letters. Use the option --ignore-warnings to proceed.']

I really hope to receive your reply, thank you！

**Comment by 123xiaochen** [comment]
I found the reason for this problem. The reason is that the 2.0.15 version of diamond is too high, and the error will not occur if it is reduced to version 2.0.9.
