### ISSUE TITLE
Antismash RuntimeError

### ISSUE THREAD

**Issue by ZhengJinfang1220** [antismash/antismash#712]
Dear Antismash developer, 

I used antismash to analysis my Metagenome data, but it came with the problem,
antismsash version: 7.0.1
installed by conda with python 3.9.

command:
`antismash --cb-knownclusters --cb-subclusters --rre --cc-mibig --output-dir Zap3.bgc --genefinding-gff3 ..    /Zap3/Zap3.gff3 "../Zap3/Zap3_output"/final.contigs.fa -c 10`

continue on the unfinished job:
`antismash --cb-knownclusters --cb-subclusters --rre --cc-mibig --reuse-results Zap3.bgc --genefinding-gff3 ..    /Zap3/Zap3.gff3 "../Zap3/Zap3_output"/final.contigs.fa -c 10`

However, I got the following error message,
```
Traceback (most recent call last):
  File "/common/yinlab/jinfang/miniconda3/envs/antismash/bin/antismash", line 8, in <module>
    sys.exit(entrypoint())
  File "/common/yinlab/jinfang/miniconda3/envs/antismash/lib/python3.9/site-packages/antismash/__main__.py", line 124, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/common/yinlab/jinfang/miniconda3/envs/antismash/lib/python3.9/site-packages/antismash/__main__.py", line 112, in main
    antismash.run_antismash(sequence, options)
  File "/common/yinlab/jinfang/miniconda3/envs/antismash/lib/python3.9/site-packages/antismash/main.py", line 676, in run_antismash
    result = _run_antismash(sequence_file, options)
  File "/common/yinlab/jinfang/miniconda3/envs/antismash/lib/python3.9/site-packages/antismash/main.py", line 727, in _run_antismash
    prepare_output_directory(options.output_dir, sequence_file or options.reuse_results)
  File "/common/yinlab/jinfang/miniconda3/envs/antismash/lib/python3.9/site-packages/antismash/main.py", line 331, in prepare_output_directory
    raise RuntimeError("Output directory contains other files, aborting for safety")
RuntimeError: Output directory contains other files, aborting for safety
```

It seems the output folder contains the other files. But, I checked the output folder, it only contains the output of antismash,

```
drwxr-xr-x  2 jinfang yinlab  41K Apr 17 18:25 knownclusterblast
-rw-r--r--  1 jinfang yinlab 4.7K Apr 17 19:00 knownclusterblastoutput.txt
-rw-r--r--  1 jinfang yinlab  141 Apr 17 19:00 subclusterblastoutput.txt

```
So how can I solve this issue, just remove the output folders and rerun the job gain?
Thanks

Best, 
Jinfang Zheng

**Comment by SJShaw** [comment]
Yes, remove the output directory or it's contents and try again.

The only exception to not allowing contents in an output directory is when that directory contains results that are explicitly reused with `--reuse`.
